upload-969 standard health check response from healthcheck function
CDCgov/data-exchange-upload pull request #224
Opened 2024-02-09 21:23 UTC by USZ7

- Add standard health check response from health check function

2024-02-09 21:54 UTC, cfarmer-fearless requested changes
This is looking excellent overall!  I tested locally, and the structure of the output looks good.  However, I'm seeing weird values of the overall duration and error messages for a few of the destination storage accounts.

```
{
    "Status": "DOWN",
    "TotalChecksDuration": "PT1.888S",
    "DependencyHealthChecks": [
        {
            "Service": "aims-celr-csv",
            "Status": "UP",
            "HealthIssues": "Healthy"
        },
        {
            "Service": "aims-celr-hl7",
            "Status": "UP",
            "HealthIssues": "Healthy"
        },
        {
            "Service": "daart-hl7",
            "Status": "UP",
            "HealthIssues": "Healthy"
        },
        {
            "Service": "dex-hl7-hl7ingress",
            "Status": "UP",
            "HealthIssues": "Healthy"
        },
        {
            "Service": "dextesting-testevent1",
            "Status": "UP",
            "HealthIssues": "Healthy"
        },
        {
            "Service": "ndlp-routineImmunization",
            "Status": "DOWN",
            "HealthIssues": "The specifed resource name contains invalid characters.\nRequestId:2c8e6d5d-a01e-0022-71a1-5bab09000000\nTime:2024-02-09T21:48:08.9815470Z\r\nStatus: 400 (The specifed resource name contains invalid characters.)\r\nErrorCode: InvalidResourceName\r\n\r\nContent:\r\n﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.\nRequestId:2c8e6d5d-a01e-0022-71a1-5bab09000000\nTime:2024-02-09T21:48:08.9815470Z</Message></Error>\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 2c8e6d5d-a01e-0022-71a1-5bab09000000\r\nx-ms-client-request-id: f3eb713a-2609-4d83-80c9-3aec3019784d\r\nx-ms-version: 2021-12-02\r\nx-ms-error-code: InvalidResourceName\r\nDate: Fri, 09 Feb 2024 21:48:08 GMT\r\nContent-Length: 243\r\nContent-Type: application/xml\r\n"
        },
        {
            "Service": "ndlp-influenzaVaccination",
            "Status": "DOWN",
            "HealthIssues": "The specifed resource name contains invalid characters.\nRequestId:2c8e6ddc-a01e-0022-65a1-5bab09000000\nTime:2024-02-09T21:48:09.1164712Z\r\nStatus: 400 (The specifed resource name contains invalid characters.)\r\nErrorCode: InvalidResourceName\r\n\r\nContent:\r\n﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.\nRequestId:2c8e6ddc-a01e-0022-65a1-5bab09000000\nTime:2024-02-09T21:48:09.1164712Z</Message></Error>\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 2c8e6ddc-a01e-0022-65a1-5bab09000000\r\nx-ms-client-request-id: b6774aa1-ab83-4b45-99c3-acc8e91577f2\r\nx-ms-version: 2021-12-02\r\nx-ms-error-code: InvalidResourceName\r\nDate: Fri, 09 Feb 2024 21:48:08 GMT\r\nContent-Length: 243\r\nContent-Type: application/xml\r\n"
        },
        {
            "Service": "ndlp-rsvPrevention",
            "Status": "DOWN",
            "HealthIssues": "The specifed resource name contains invalid characters.\nRequestId:2c8e6e2f-a01e-0022-35a1-5bab09000000\nTime:2024-02-09T21:48:09.1974243Z\r\nStatus: 400 (The specifed resource name contains invalid characters.)\r\nErrorCode: InvalidResourceName\r\n\r\nContent:\r\n﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.\nRequestId:2c8e6e2f-a01e-0022-35a1-5bab09000000\nTime:2024-02-09T21:48:09.1974243Z</Message></Error>\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 2c8e6e2f-a01e-0022-35a1-5bab09000000\r\nx-ms-client-request-id: 7f17fa29-6414-44e5-82c8-7d865806a678\r\nx-ms-version: 2021-12-02\r\nx-ms-error-code: InvalidResourceName\r\nDate: Fri, 09 Feb 2024 21:48:08 GMT\r\nContent-Length: 243\r\nContent-Type: application/xml\r\n"
        },
        {
            "Service": "ndlp-covidallmonthlyVaccination",
            "Status": "DOWN",
            "HealthIssues": "The specifed resource name contains invalid characters.\nRequestId:2c8e6e7c-a01e-0022-80a1-5bab09000000\nTime:2024-02-09T21:48:09.2733817Z\r\nStatus: 400 (The specifed resource name contains invalid characters.)\r\nErrorCode: InvalidResourceName\r\n\r\nContent:\r\n﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.\nRequestId:2c8e6e7c-a01e-0022-80a1-5bab09000000\nTime:2024-02-09T21:48:09.2733817Z</Message></Error>\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 2c8e6e7c-a01e-0022-80a1-5bab09000000\r\nx-ms-client-request-id: a0f75ce0-0532-4e15-a99c-5e2ccc612080\r\nx-ms-version: 2021-12-02\r\nx-ms-error-code: InvalidResourceName\r\nDate: Fri, 09 Feb 2024 21:48:08 GMT\r\nContent-Length: 243\r\nContent-Type: application/xml\r\n"
        },
        {
            "Service": "ndlp-covidbridgeVaccination",
            "Status": "DOWN",
            "HealthIssues": "The specifed resource name contains invalid characters.\nRequestId:2c8e6ebe-a01e-0022-41a1-5bab09000000\nTime:2024-02-09T21:48:09.3483397Z\r\nStatus: 400 (The specifed resource name contains invalid characters.)\r\nErrorCode: InvalidResourceName\r\n\r\nContent:\r\n﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.\nRequestId:2c8e6ebe-a01e-0022-41a1-5bab09000000\nTime:2024-02-09T21:48:09.3483397Z</Message></Error>\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 2c8e6ebe-a01e-0022-41a1-5bab09000000\r\nx-ms-client-request-id: 9a3c79a9-ce3f-4903-a303-3012f3995ab9\r\nx-ms-version: 2021-12-02\r\nx-ms-error-code: InvalidResourceName\r\nDate: Fri, 09 Feb 2024 21:48:08 GMT\r\nContent-Length: 243\r\nContent-Type: application/xml\r\n"
        },
        {
            "Service": "ndlp-aplHistoricalData",
            "Status": "DOWN",
            "HealthIssues": "The specifed resource name contains invalid characters.\nRequestId:2c8e6f0d-a01e-0022-09a1-5bab09000000\nTime:2024-02-09T21:48:09.4302919Z\r\nStatus: 400 (The specifed resource name contains invalid characters.)\r\nErrorCode: InvalidResourceName\r\n\r\nContent:\r\n﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.\nRequestId:2c8e6f0d-a01e-0022-09a1-5bab09000000\nTime:2024-02-09T21:48:09.4302919Z</Message></Error>\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 2c8e6f0d-a01e-0022-09a1-5bab09000000\r\nx-ms-client-request-id: 6c320983-56cc-4b4e-ac53-90f04e54c328\r\nx-ms-version: 2021-12-02\r\nx-ms-error-code: InvalidResourceName\r\nDate: Fri, 09 Feb 2024 21:48:08 GMT\r\nContent-Length: 243\r\nContent-Type: application/xml\r\n"
        },
        {
            "Service": "pulsenet-LocalSequenceFile",
            "Status": "DOWN",
            "HealthIssues": "The specifed resource name contains invalid characters.\nRequestId:2c8e6f53-a01e-0022-4fa1-5bab09000000\nTime:2024-02-09T21:48:09.5222404Z\r\nStatus: 400 (The specifed resource name contains invalid characters.)\r\nErrorCode: InvalidResourceName\r\n\r\nContent:\r\n﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.\nRequestId:2c8e6f53-a01e-0022-4fa1-5bab09000000\nTime:2024-02-09T21:48:09.5222404Z</Message></Error>\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 2c8e6f53-a01e-0022-4fa1-5bab09000000\r\nx-ms-client-request-id: 1dbe8a68-14fa-47ac-9a29-c0e2ba9346ef\r\nx-ms-version: 2021-12-02\r\nx-ms-error-code: InvalidResourceName\r\nDate: Fri, 09 Feb 2024 21:48:08 GMT\r\nContent-Length: 243\r\nContent-Type: application/xml\r\n"
      [...]

2024-02-09 21:54 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/HealthCheckFunctionTests.cs
> +            Assert.AreEqual("UP", healthCheckResponse.Status);
Let's also assert that the dependent health check service contains the correct destination and event.

2024-02-09 21:54 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                _logger.LogInformation("destinations-->" + destinations);
Let's set this log level to debug instead of information.  It produces a very large output.

2024-02-09 22:20 UTC, dancing-goats commented on upload-processor/BulkFileUploadFunctionApp/Model/HealthCheckResponse.cs
> +    public List<HealthCheckResult> DependencyHealthChecks { get; set; } = new List<HealthCheckResult>(); // Results of individual dependency health checks.
To use `List<>`, do you need to bring in the `using System.Collections.Generic` library? 

You can also initialize `DependencyHealthChecks` with simply `new()`:

```bash
public List<HealthCheckResult> DependencyHealthChecks { get; set; } = new(); 
```

2024-02-09 22:20 UTC, dancing-goats commented on upload-processor/BulkFileUploadFunctionApp/Model/HealthCheckResult.cs
> +
nit: extra line at the top here

2024-02-09 22:20 UTC, dancing-goats commented on upload-processor/BulkFileUploadFunctionApp/Model/HealthCheckResponse.cs
> +
nit: extra line at the top here

2024-02-09 22:20 UTC, dancing-goats commented on upload-processor/BulkFileUploadFunctionApp/Model/HealthCheckResult.cs
> +    public HealthCheckResult(string service, string status, string healthIssues = "")
Add null checks to ensure `service`, `status`, and `healthIssues` is not null.

2024-02-09 22:20 UTC, dancing-goats commented on upload-processor/BulkFileUploadFunctionApp/Services/StorageContentReader.cs
> +            // Download the blob's contents as a string
Consider adding async implementation for downloading blob content and adding error handling to check if the blob exists before download attempt.

2024-02-12 13:23 UTC, cfarmer-fearless requested changes

2024-02-12 13:23 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                string destinations = _storageContentReader.GetContent(blobServiceClient, TestContainerName, TestBlobName);
So looks like this will only verify the connection to the dex storage account.  According to the ticket, we need to also verify connection to the edav and routing storage accounts.  Let's rework this a bit to verify connections to these storage accounts.

2024-02-12 13:23 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                foreach (var destination in listOfDestinations)
Thinking about this a bit more; we probably don't need to loop through each destination, especially because they get created on the fly if they don't exist.  We really just need to test the connection to the storage account.  I think we can do this by connecting to just one blob container that we know is there, like the dextesting container.

2024-02-13 13:46 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/Model/HealthCheckResponse.cs
> +    public List<HealthCheckResult> DependencyHealthChecks { get; set; } = new List<HealthCheckResult>(); // Results of individual dependency health checks.
> To use `List<>`, do you need to bring in the `using System.Collections.Generic` library?
> 
> You can also initialize `DependencyHealthChecks` with simply `new()`:
> 
> ```shell
> public List<HealthCheckResult> DependencyHealthChecks { get; set; } = new(); 
> ```

Done!

2024-02-13 13:48 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +            }
> In C#, you can use LINQ to simplify querying. Instead of using a double loop, you can do:
> 
> ```shell
>     var concatenatedList = destinations
>         .Where(destination => destination?.extEvents != null)
>         .SelectMany(destination => destination.extEvents
>             .Where(extEvent => extEvent?.name != null)
>             .Select(extEvent => $"{destination.destinationId}-{extEvent.name}"))
>         .ToList();
> ```

The idea has been changed. We don't need this code. It is removed.

2024-02-13 13:48 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/Model/HealthCheckResult.cs
> +
> nit: extra line at the top here

Fixed.

2024-02-13 13:48 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/Model/HealthCheckResponse.cs
> +
> nit: extra line at the top here

Fixed.

2024-02-13 13:49 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/Model/HealthCheckResult.cs
> +    public HealthCheckResult(string service, string status, string healthIssues = "")
> Add null checks to ensure `service`, `status`, and `healthIssues` is not null.

Done.

2024-02-13 13:51 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/Services/StorageContentReader.cs
> +            // Download the blob's contents as a string
> Consider adding async implementation for downloading blob content and adding error handling to check if the blob exists before download attempt.

we don't need this code any more. It's removed.

2024-02-13 13:51 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                string destinations = _storageContentReader.GetContent(blobServiceClient, TestContainerName, TestBlobName);
> So looks like this will only verify the connection to the dex storage account. According to the ticket, we need to also verify connection to the edav and routing storage accounts. Let's rework this a bit to verify connections to these storage accounts.

Done.

2024-02-13 13:52 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                foreach (var destination in listOfDestinations)
> Thinking about this a bit more; we probably don't need to loop through each destination, especially because they get created on the fly if they don't exist. We really just need to test the connection to the storage account. I think we can do this by connecting to just one blob container that we know is there, like the dextesting container.

Done.

2024-02-13 14:30 UTC, cfarmer-fearless requested changes

2024-02-13 14:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +        public string[] StorageNames = { "EDAV Blob Container", "Routing Blob Container" };
Can make this `private readonly`

2024-02-13 14:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                    else
Need another `else if` here to do the EDAV storage account too

2024-02-13 14:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                BlobContainerClient container = blobServiceClient.GetBlobContainerClient(destination == "Routing Blob Container" ? "test-routing" : "dextesting-testevent1");
Checking if the destination is the routing container seems error prone.  Ideally, this function shouldn't be aware of the specific storage container it's connecting to.  Perhaps you can determine the correct blob container (test-routing vs dextesting-testevent1) before calling the `CheckBlobStorageHealthAsync` function.

2024-02-13 14:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +        private async Task<HealthCheckResult> CheckBlobStorageHealthAsync(string destination, BlobServiceClient blobServiceClient)
This function does not need to be `async`.

2024-02-13 14:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +            catch (RequestFailedException ex)
Don't we want to use the exception message in the health check result?

2024-02-13 17:42 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +            catch (RequestFailedException ex)
> Don't we want to use the exception message in the health check result?

Fixed.

2024-02-13 17:43 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                BlobContainerClient container = blobServiceClient.GetBlobContainerClient(destination == "Routing Blob Container" ? "test-routing" : "dextesting-testevent1");
> Checking if the destination is the routing container seems error prone. Ideally, this function shouldn't be aware of the specific storage container it's connecting to. Perhaps you can determine the correct blob container (test-routing vs dextesting-testevent1) before calling the `CheckBlobStorageHealthAsync` function.

Done.

2024-02-13 17:46 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +        private async Task<HealthCheckResult> CheckBlobStorageHealthAsync(string destination, BlobServiceClient blobServiceClient)
> This function does not need to be `async`.

removing 'async', but that caused an error, so I left it as it was.

2024-02-14 12:30 UTC, USZ7 commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                    else
> Need another `else if` here to do the EDAV storage account too

Done!

2024-02-14 14:38 UTC, cfarmer-fearless requested changes

2024-02-14 14:38 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +        private async Task<HealthCheckResult> CheckBlobStorageHealthAsync(string destination, string containerName,BlobServiceClient blobServiceClient,ILogger logger)
Let's make logger a private readonly member of this class so we don't need to pass it in.

2024-02-14 16:20 UTC, dancing-goats approved these changes

2024-02-14 21:02 UTC, cfarmer-fearless approved these changes

2024-02-14 21:10 UTC, merged