UPLOAD-915: blob copy retry and replay
CDCgov/data-exchange-upload pull request #237
Opened 2024-02-23 14:14 UTC by rohitpanwar

2024-02-23 16:30 UTC, cfarmer-fearless requested changes

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +        public async Task ProcessBlob(string? blobCreatedUrl)
Make `blobCreateUrl` non-null here since we shouldn't be calling this function unless we have a blob creation url.

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                var connectionString = $"DefaultEndpointsProtocol=https;AccountName={_dexAzureStorageAccountName};AccountKey={_dexAzureStorageAccountKey};EndpointSuffix=core.windows.net";
This connection string can be a private readonly class variable.

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                var sourceContainerName = _tusAzureStorageContainer;
`sourceContainerName` variable is unnecessary.

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                tusInfoFile = await GetTusFileInfo(connectionString, sourceContainerName, tusPayloadPathname);
Define and initialize `tusInfoFile` here so you can define it as non-null.

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +
Throw an error here if `tusInfoFile` is null.  See example on main branch.

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                // START SPAN
I think we should start the span as soon as possible to capture the actual duration of the execution of his function.  I think we want it to include all of the pre-req steps.

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            try
This try/catch is unnecessary as `CreateReport` has internal exception handling and should never throw an exception

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            try
This try/catch is unnecessary as `CreateReport` has internal exception handling and should never throw an exception

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                if(dexBlobUrl == null) {
Why are we checking for `dexBlobUrl` here?

2024-02-23 16:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                try
This try/catch is unnecessary as `StopSpanForTrace` has internal exception handling and should never through an exception.

2024-02-23 17:17 UTC, cfarmer-fearless requested changes

2024-02-23 18:13 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +                blobCopyRetryEvent.retryAttempt = 1;
will add

2024-02-23 18:15 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +            if (blobCopyRetryEvent.retryAttempt == MAX_RETRY_ATTEMPTS) {
This is working as expected. I start with attempt 1 not 0 and for  hats why comparison is <=  . we can probably do a screen share to go over this logic

2024-02-23 18:17 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +                        await Task.Delay(1000 * blobCopyRetryEvent.retryAttempt);
adding some delay to try for the second time. just in case a second delay (Exponential backoff) resolves the issue in first attempt. I can remove this and keeping this is not doing any harm either I think.

2024-02-23 18:18 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +                    if(blobCopyRetryEvent.retryAttempt <= MAX_RETRY_ATTEMPTS) {
this logic is working fine. we can do a teams call to go over this.

2024-02-23 18:22 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +                if(blobCopyRetryEvent.copyRetryStage != null) {
will look into this

2024-02-23 18:25 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +        private const int MAX_RETRY_ATTEMPTS = 2;
forgot to add to app setting. that was the plan :) will add now

2024-02-26 03:37 UTC, dancing-goats commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadEventHubService.cs
> +            string jsonPayload = null;
Do you need this declaration: `string jsonPayload = null;`?

You can handle this with `string jsonPayload = JsonSerializer.Serialize(blobCopyRetryEvent);`

```csharp
public async Task PublishRetryEvent(BlobCopyRetryEvent blobCopyRetryEvent)
{
    string jsonPayload = JsonSerializer.Serialize(blobCopyRetryEvent);

    try
    {
        _logger.LogInformation("Publishing Retry Event: {jsonPayload}", jsonPayload);

        await PublishEventAsync(_retryEventHubProducerClient, jsonPayload);

        _logger.LogInformation("Retry event published successfully");
    }
    catch (Exception e)
    {
        _logger.LogError(e, "Failed to publish Retry event: {jsonPayload}", jsonPayload);
    }
}
```

2024-02-26 03:37 UTC, dancing-goats commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorReplay.cs
> +                    }
Is this a redundant else block?

2024-02-26 07:11 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                    return;
finally will always execute

2024-02-26 07:13 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorReplay.cs
> +                    }
it's not a redundant else block

2024-02-26 07:15 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadEventHubService.cs
> +            string jsonPayload = null;
trying to make it available in catch block for logs

2024-02-26 07:17 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                if(dexBlobUrl == null) {
the idea was is any exception before even getting dexBlobUrl, it's probably something else that we can not process the blob. rethinking this and removed. I think we should put it on retry anyway.

2024-02-26 07:20 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                try
this is to catch if there is any error getting the configuration

2024-02-26 07:22 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            try
This is required. The function can be called independently to copy only from dex to routing for a retry attempt.

2024-02-26 07:22 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            try
This is required. The function can be called independently to copy only from dex to edav for a retry attempt.

2024-02-26 07:23 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            try
removed

2024-02-26 07:23 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            try
removed

2024-02-26 07:24 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                // START SPAN
sure

2024-02-26 07:26 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +
made the change but printing log error and returning in case of no ID instead of throwing an exception

2024-02-26 13:20 UTC, cfarmer-fearless requested changes

2024-02-26 13:20 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                try
That shouldn't happen.  The way it's coded up now, `ExecuteIfEnabledAsync` should never throw

2024-02-26 13:20 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorReplay.cs
> +                    }
I also think it's redundant.  Call `await ProcessEvent(partitionEvent)` above the if statement, and just have the `break` inside the if statement with no `else`.

2024-02-26 13:20 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            try
It's not required.  It is unnecessary to catch and then throw again.

2024-02-26 14:29 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                        string errorDesc =  $"Failed to copy from Dex to ROUTING. {ex.Message}";
Should be "failed to copy from dex to edav"

2024-02-26 14:33 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                    return;
Throw exception here instead of return early.

2024-02-26 16:10 UTC, cfarmer-fearless approved these changes

2024-02-26 16:15 UTC, merged