upload-1017 integration tests using node typescript and playwright
CDCgov/data-exchange-upload pull request #246
Opened 2024-02-29 15:26 UTC by USZ7

-Integration tests using node typescript and playwright.

2024-02-29 22:46 UTC, cfarmer-fearless requested changes

2024-02-29 22:46 UTC, cfarmer-fearless commented on tests/integration/playwright/index.ts
> +export async function getTraceResponse(uploadId: string, accessToken: string): Promise<void> {
Don't need to pass an access token to PS API

2024-02-29 22:46 UTC, cfarmer-fearless commented on tests/integration/playwright/index.ts
> +      if (matches && matches[1]) {
Instead of doing this, use the `onUploadUrlAvailable()` to get the upload ID

2024-02-29 22:46 UTC, cfarmer-fearless commented on tests/integration/playwright/index.ts
> +        getTraceResponse(uploadId, loginResponse.accessToken);
Why do this here?

2024-02-29 22:46 UTC, cfarmer-fearless commented on tests/integration/playwright/index.ts
> +  return { uploadId, accessToken: loginResponse.accessToken };
I don't think this `return` will wait until the upload is complete

2024-02-29 22:46 UTC, cfarmer-fearless commented on tests/integration/playwright/index.ts
> +  if (loginResponse === null) {
Logging in and uploading a file should be totally decoupled.

2024-02-29 22:46 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +    const result = await start();
The access token and upload ID should be decoupled.  Should be more like 
First: login and get access token
Second: Upload a file and get upload ID when complete

2024-02-29 22:46 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +    expect(uploadId).toBeTruthy();
You should expect it to equal an actual string value, not just truthy.

2024-02-29 22:46 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +    const traceResponse = await getTraceResponse(uploadId, accessToken);
I would like these API calls to use Playwright's API context instead of Axios. https://playwright.dev/java/docs/api-testing#introduction

2024-03-04 14:27 UTC, cfarmer-fearless requested changes
Still some work to do.  Please also create a README.md in the `playwright` directory with instructions on how to run these tests.

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/client.ts
> +      console.log("Raw response data:", response.data);
Let's make sure to remove this log before it goes into main.  We don't want to be logging this data.  It's fine for debugging though

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +      psApiUrl = `${config.validateEnv()[3]}/api/trace/uploadId/${uploadId}`;
I don't like having to get specific environment variables by indexing an array.  We should be able to get them by passing a key representing the variable's name.  In NodeJS, this is typically done with `process.env`.

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/package.json
> +  "dependencies": {
Should there be a playwright dependency here?  See playwright installation docs: https://playwright.dev/docs/intro

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/package.json
> +    "axios": "^1.6.7",
Hoping we can remove `axios` as a dependency and just use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch).

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/package.json
> +    "express": "^4.17.1",
What do we need `express` for?

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +      psApiUrl = `${config.validateEnv()[3]}/api/trace/uploadId/${uploadId}`;
Also, since tracing is currently broken on the PS API, let's validate data against the report endpoint instead.

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +    // Act: Query the PS API with the obtained uploadId and accessToken
Again, the PS API doesn't need an access token.  It can be removed from the request headers.  It's only needed for uploading a file.

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +    expect(responseBody).toHaveProperty('expectedProperty');
Shouldn't we have an actual expected value instead of just a string "expectedProperty"?  Seems like this code was just copy/pasted from somewhere.

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/upload.ts
> +  const [_, __, url] = config.validateEnv();
Since we only need the url here, let's just get it from the environment variables directly with `process.env`.

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/upload.ts
> +export async function uploadFileAndGetId(accessToken) {
Let's pass the filename here so we can upload different files.

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/upload.ts
> +      endpoint: `${url}/upload`,
Let's pass the entire url and path instead of just the url so we can bypass APIM if we need to.

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/upload.ts
> +      metadata: {
Let's pass in this metadata so we have the ability to create tests based on certain metadata.  It may help to create helper functions to create metadata objects.

2024-03-04 14:27 UTC, cfarmer-fearless commented on tests/integration/playwright/upload.ts
> +    return new Promise((resolve, reject) => {
Does this need to return a promise?  Everything should be synchronous.

2024-03-04 14:34 UTC, cfarmer-fearless commented on tests/integration/playwright/client.ts
> +  async login(username: string, password: string, url: string): Promise<LoginResponse | null> {
Everywhere you have `Type | null` you can replace with the shorthand version `Type?` with a question mark at the end.

2024-03-04 22:17 UTC, USZ7 commented on tests/integration/playwright/client.ts
> +      console.log("Raw response data:", response.data);
Done.

2024-03-04 22:17 UTC, USZ7 commented on tests/integration/playwright/test/upload-test.spec.ts
> +      psApiUrl = `${config.validateEnv()[3]}/api/trace/uploadId/${uploadId}`;
Done.

2024-03-04 22:21 UTC, USZ7 commented on tests/integration/playwright/package.json
> +  "dependencies": {
Playwright is used for development testing and automation, not in production, so it should be listed as a devDependency in package.json.

2024-03-04 22:21 UTC, USZ7 commented on tests/integration/playwright/package.json
> +    "axios": "^1.6.7",
Done.

2024-03-04 22:22 UTC, USZ7 commented on tests/integration/playwright/package.json
> +    "express": "^4.17.1",
removed.

2024-03-04 22:22 UTC, USZ7 commented on tests/integration/playwright/upload.ts
> +  const [_, __, url] = config.validateEnv();
Done.

2024-03-04 22:22 UTC, USZ7 commented on tests/integration/playwright/upload.ts
> +export async function uploadFileAndGetId(accessToken) {
Done.

2024-03-04 22:23 UTC, USZ7 commented on tests/integration/playwright/upload.ts
> +      endpoint: `${url}/upload`,
Done.

2024-03-04 22:23 UTC, USZ7 commented on tests/integration/playwright/upload.ts
> +      metadata: {
Done.

2024-03-04 22:23 UTC, USZ7 commented on tests/integration/playwright/upload.ts
> +    return new Promise((resolve, reject) => {
Fixed.

2024-03-04 22:25 UTC, USZ7 commented on tests/integration/playwright/login.ts
> +  const loginResponse: LoginResponse | null = await c.login(username, password, url);
tried to make the change as you suggested, but it caused an error.

2024-03-04 22:26 UTC, USZ7 commented on tests/integration/playwright/config.ts
> +    const username = process.env.SAMS_USERNAME || process.env.ACCOUNT_USERNAME;
Done.

2024-03-05 13:23 UTC, cfarmer-fearless requested changes

2024-03-05 13:23 UTC, cfarmer-fearless commented on tests/integration/playwright/README.md
> +To run the script, invoke NodeJS passing the script name as its first argument, as in `node index.js`. You should get console output similar to this:
According to the docs, playwright tests are run with `npx playwright test`.  Can we run the tests with this command instead of running a javascript file directly?

2024-03-05 13:23 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +  test('upload and get trace response', async ({ request }) => {
The tests should cover the following cases:

- should return 500 with error message when destination ID not provided; PS API should return complete for metadata verify with equal error message
- should return 500 with error message when event type not provided; PS API should return complete for metadata verify with equal error message
- should return 500 with error message when destination ID and event type are mismatched; PS API should return complete for metadata verify with equal error message
- should return 500 when config schema definition invalid; PS API should return complete for metadata verify with equal error message

2024-03-06 19:08 UTC, USZ7 commented on tests/integration/playwright/test/upload-test.spec.ts
> +  test('upload and get trace response', async ({ request }) => {
Done.

2024-03-06 19:09 UTC, USZ7 commented on tests/integration/playwright/README.md
> +To run the script, invoke NodeJS passing the script name as its first argument, as in `node index.js`. You should get console output similar to this:
Done.

2024-03-06 19:09 UTC, USZ7 commented on tests/integration/playwright/client.ts
> +import axios from "axios";
Done.

2024-03-06 20:00 UTC, cfarmer-fearless requested changes

2024-03-06 20:00 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +    const metadata = createMetadata({ destinationId: undefined, eventType: "testevent1" });
This test should provide metadata without the `destinationId` field itself.  Here, you are providing the field with an undefined value.  Even though the value is undefined, you are still providing the field.

2024-03-06 20:00 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +    const metadata = createMetadata({ destinationId: "dextesting", eventType: undefined });
Same here but for `eventType`.

2024-03-06 20:00 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +  test('upload and get trace response', async ({ request }) => {
The assersions against the PS API response also need to verify the `issues` field contains the same error message that was given in the tus response.  It may be better to do these queries as part of your four tests above.

2024-03-08 16:25 UTC, cfarmer-fearless requested changes

2024-03-08 16:25 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +import dotenv from "dotenv";
Please use consistent quotation marks

2024-03-08 16:25 UTC, cfarmer-fearless commented on tests/integration/playwright/test/upload-test.spec.ts
> +        const response = await request.get(psApiUrl, { headers: { Authorization: `Bearer ${accessToken}` } });
The PS API does not need an auth token in the HTTP request.

2024-03-08 18:44 UTC, USZ7 commented on tests/integration/playwright/test/upload-test.spec.ts
> +        const response = await request.get(psApiUrl, { headers: { Authorization: `Bearer ${accessToken}` } });
Done.

2024-03-08 18:45 UTC, USZ7 commented on tests/integration/playwright/test/upload-test.spec.ts
> +import dotenv from "dotenv";
Fixed.

2024-03-08 18:46 UTC, USZ7 commented on tests/integration/playwright/test/upload-test.spec.ts
> +    uploadId = uploadIdMatch ? uploadIdMatch[1] : null;
We can't set the uploadId from the result of client.uploadFileAndGetId if the upload fails. For non-happy paths, we must extract the uploadId from the error.

2024-03-11 17:35 UTC, merged