replay bug and other code refactoring
CDCgov/data-exchange-upload pull request #252
Opened 2024-03-04 15:51 UTC by rohitpanwar

https://cdc-dexops.atlassian.net/browse/UPLOAD-1055

2024-03-04 17:51 UTC, cfarmer-fearless requested changes

2024-03-04 17:51 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Model/BlobCopyRetryEvent.cs
> +        [JsonPropertyName("uploadId")]
Combine to `CopyPrereq` object

2024-03-04 17:51 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Model/CopyPreqs.cs
> +        public CopyPreqs()
Use `.Default`

2024-03-04 21:05 UTC, cfarmer-fearless requested changes

2024-03-04 21:05 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
>  {
Remove unused private variables `_configuration` and `_uploadConfigStorageContainer`

2024-03-04 21:11 UTC, cfarmer-fearless requested changes

2024-03-04 21:11 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorReplay.cs
>  using Microsoft.Extensions.Logging;
Remove unused imports `System.Text.Json` and `Azure.messaging.eventhubs.consumer`

2024-03-04 21:11 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorReplay.cs
>          [Function("UploadProcessorReplay")]
Missing an `await` on line 58 for `ProcessReplayEventHubEventsAsync`

2024-03-04 21:11 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +                if(blobCopyRetryEvent.CopyRetryStage == null)
Unnecessary if statement.  The copy stage will never be null.

2024-03-04 21:11 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +                                _uploadProcessingService.CopyAll(copyPrereqs);
Add `await`

2024-03-04 22:24 UTC, cfarmer-fearless commented
Seeing the following copy prereq while testing:
```
Copy preqs: {"UploadId":null,"SourceBlobUrl":"https://ocioededataexchangedev.blob.core.windows.net/bulkuploads/tus-prefix/23434103d60b20c497bbad8012115e86","TusPayloadFilename":"/tus-prefix/23434103d60b20c497bbad8012115e86","DexBlobUrl":null,"DestinationId":"dextesting","EventType":"testevent1","DexBlobFolderName":"dextesting-testevent1","DexBlobFileName":"2024/03/04/10KB-test-file_638451874617914803","Metadata":{"meta_destination_id":"dextesting","meta_ext_event":"testevent1","meta_ext_source":"INTEGRATION-TEST","sender_id":"INTEGRATION-TEST","data_producer_id":"","jurisdiction":"","received_filename":"10KB-test-file","data_stream_id":"dextesting","data_stream_route":"testevent1","version":"2.0","tus_tguid":"23434103d60b20c497bbad8012115e86","upload_id":"23434103d60b20c497bbad8012115e86","trace_id":"TracingDisabled","span_id":"TracingDisabled"},"Targets":[{"target":"dex_edav"},{"target":"dex_routing"}],"Trace":{"TraceId":"TracingDisabled","SpanId":"TracingDisabled","UploadId":"TracingDisabled","DestinationId":null,"EventType":null}}
```
Note that UploadId and DexBlobUrl are null, but there are fields called `upload_id` and `SourceBlobUrl` that are populated.  Should these fields be combined?

2024-03-04 22:30 UTC, cfarmer-fearless requested changes

2024-03-04 22:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                _logger.LogInformation($"Copy Targets: {targets}");
You'll need to either serialize this to a JSON string or loop through each item in the list (probably using Linq) in order to print out the actual values.  This just prints the class name.

2024-03-04 22:58 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorReplay.cs
>          [Function("UploadProcessorReplay")]
this is on purpose. Do not want to wait for everything to complete before returning back Http response

2024-03-04 22:58 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +                if(blobCopyRetryEvent.CopyRetryStage == null)
will remove this extra check

2024-03-04 22:59 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorRetry.cs
> +                                _uploadProcessingService.CopyAll(copyPrereqs);
done

2024-03-04 23:01 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
>  {
done

2024-03-04 23:03 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/UploadProcessorReplay.cs
>  using Microsoft.Extensions.Logging;
done

2024-03-04 23:04 UTC, rohitpanwar commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                _logger.LogInformation($"Copy Targets: {targets}");
removing this as I am printing copy prereqs elsewhere for debugging purposes

2024-03-05 00:45 UTC, cfarmer-fearless approved these changes

2024-03-05 01:35 UTC, merged