Upload 949 BulkUploadFunction unit tests
CDCgov/data-exchange-upload pull request #261
Opened 2024-03-11 17:21 UTC by tedtally

Please review the small modifications to the codebase that help facilitate the running of BulkFileUploadFunction's (only) unit tests.

2024-03-12 12:01 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +        public void GivenValidUri_WhenRunIsCalled_ThenBlobIsValidated()
I don't understand the purpose of this test.  It appears to just be verifying that an object was serialized properly.  What is the actual unit under test for this test?

2024-03-12 12:06 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +using Microsoft.VisualStudio.TestTools.UnitTesting;
Remove all unused `using` statements.

2024-03-12 12:06 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +        private Mock<IProcStatClient>? _mockProcStatClient;
Remove all unused mocks

2024-03-12 12:08 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            var mockUriWrapper = new Mock<IUriWrapper>();
We shouldn't need to mock the Uri since we are mocking the upload processing service.

2024-03-12 12:10 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            var blobReaderMock = new Mock<IBlobReader>();
This mock is probably unnecessary since you are mocking the upload processing service

2024-03-12 12:11 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            _mockTusInfoFileStorage = new MockTusStorage { Container = "bulkuploads", Key = "tus-prefix/a0e127caec153d6047ee966bc2acd8cb", Type = "azurestore" };
What is this mock used for?

2024-03-12 12:12 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            TusInfoFile tusInfoFile = new TusInfoFile
Many of these objects are likely not needed.  As long as you can instantiate a `CopyPrereqs`, you should be good.

2024-03-12 12:17 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Utils/IBlobReader.cs
> +        Task<T> GetObjectFromBlobJsonContent<T>(string connectionString, string sourceContainerName, string blobPathname);
Make this return type `Task<T?>` to match the implementation function signature.

2024-03-12 12:19 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Utils/BlobReaderFactory.cs
> +using Azure.Storage.Blobs.Models;
Remove unused `using` statements

2024-03-12 12:22 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            TusInfoFile tusInfoFile = await _blobReader.GetObjectFromBlobJsonContent<TusInfoFile>(_dexStorageAccountConnectionString, _tusAzureStorageContainer, tusInfoFilename);
Not sure if this will work.  You've initialized `_blobReader` with `blobReaderFactory.CreateInstance(_logger)`.  Has the `blobServiceClientFactory` been initialized yet?  I believe it's null at this point.

2024-03-12 13:41 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            //var blobReader = new BlobReader(_logger);
done

2024-03-12 13:42 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                //var blobReader = new BlobReader(_logger);
done

2024-03-12 13:42 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                //var blobReader = new BlobReader(_logger);
done

2024-03-12 13:43 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +        //private UploadProcessingService _uploadProcessingService;
done

2024-03-12 13:50 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            _mockTusInfoFileStorage = new MockTusStorage { Container = "bulkuploads", Key = "tus-prefix/a0e127caec153d6047ee966bc2acd8cb", Type = "azurestore" };
It represents the Storage property for the (Mock)TusFileInfo object and I intended to use and modify it in future tests

2024-03-12 13:51 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            TusInfoFile tusInfoFile = new TusInfoFile
I agree. The original intention was to create something that can eventually be reused and modified for future tests

2024-03-12 13:51 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Utils/IBlobReader.cs
> +        Task<T> GetObjectFromBlobJsonContent<T>(string connectionString, string sourceContainerName, string blobPathname);
done

2024-03-12 13:55 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Utils/BlobReaderFactory.cs
> +using Azure.Storage.Blobs.Models;
done

2024-03-12 14:02 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            TusInfoFile tusInfoFile = await _blobReader.GetObjectFromBlobJsonContent<TusInfoFile>(_dexStorageAccountConnectionString, _tusAzureStorageContainer, tusInfoFilename);
You're right. I previously removed the references to blobServiceClientFactory but I think I missed this in the merge with main. This was rolled back to the original way knowing that we were going to go back and refactor the blobReader and Copy classes.

2024-03-12 14:17 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            TusInfoFile tusInfoFile = await _blobReader.GetObjectFromBlobJsonContent<TusInfoFile>(_dexStorageAccountConnectionString, _tusAzureStorageContainer, tusInfoFilename);
I rolled back the code to pre-BlobClientFactory version

2024-03-12 15:13 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            TusInfoFile tusInfoFile = new TusInfoFile
Understood.  We can keep there definitions, but if these instances aren't used for the test, let's remove them.

2024-03-12 18:10 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            //_loggerFactoryMock.Setup(x => x.CreateLogger(It.IsAny<string>())).Returns(_loggerMock.Object);
done

2024-03-12 18:10 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            System.Uri uri = mockUriWrapper.Object.GetUri(); //new System.Uri("https://example.com/blob/1MB-test-file");
done

2024-03-12 18:35 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            await _mockUploadProcessingService.Object.CopyAll(copyPrereqs);
We tested and confirmed that this is correct

2024-03-12 18:37 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            // Set up the BlobCopyHelper mock
Code has been removed

2024-03-12 18:37 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +        public async Task GivenNullResponseContent_WhenRunIsCalled_ThenBlobIsNotValidated()
Test has been removed

2024-03-12 18:38 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +        public void GivenValidUri_WhenRunIsCalled_ThenBlobIsValidated()
Test has been removed

2024-03-12 19:00 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +using Microsoft.VisualStudio.TestTools.UnitTesting;
done

2024-03-12 19:00 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +        private Mock<IProcStatClient>? _mockProcStatClient;
done

2024-03-12 19:00 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            var mockUriWrapper = new Mock<IUriWrapper>();
done

2024-03-12 19:01 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            var blobReaderMock = new Mock<IBlobReader>();
Removed. done.

2024-03-12 19:01 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            _mockTusInfoFileStorage = new MockTusStorage { Container = "bulkuploads", Key = "tus-prefix/a0e127caec153d6047ee966bc2acd8cb", Type = "azurestore" };
reference removed.

2024-03-12 19:01 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            TusInfoFile tusInfoFile = new TusInfoFile
removed.

2024-03-12 19:01 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            TusInfoFile tusInfoFile = await _blobReader.GetObjectFromBlobJsonContent<TusInfoFile>(_dexStorageAccountConnectionString, _tusAzureStorageContainer, tusInfoFilename);
done

2024-03-13 19:01 UTC, cfarmer-fearless requested changes
Make changes to resolve runtime errors.

2024-03-13 19:01 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +        , IUploadEventHubService uploadEventHubService, BlobReaderFactory blobReaderFactory)
Remove blob reader factory dependency injection

2024-03-13 19:01 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            _blobReader = blobReaderFactory.CreateInstance(_logger);
Remove private field for blob reader

2024-03-13 20:02 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +        , IUploadEventHubService uploadEventHubService, BlobReaderFactory blobReaderFactory)
@cfarmer-fearless  What's your thoughts on this? Instead of removing the dependency and leaving us open to multiple instances again, let's reinsert the IBlobReaderFactory class back , correct the injection statement and  services.AddSingleton<IBlobReaderFactory, BlobReaderFactory>(); to Program.cs. This way we can keep the DI and provide somewhat of a placeholder for the eventual refactor to the IBlobManagementSvc.

2024-03-14 19:29 UTC, cfarmer-fearless approved these changes

2024-03-14 20:14 UTC, merged