UPLOAD-1079: consolidate use case upload configuration and metadata json files
CDCgov/data-exchange-upload pull request #262
Opened 2024-03-13 14:45 UTC by dancing-goats

To consolidate use case upload configuration and metadata json files, revamp the json schema for v1 and v2, and refactor corresponding code. 

link: https://cdc-dexops.atlassian.net/browse/UPLOAD-1079

2024-03-13 14:57 UTC, cfarmer-fearless requested changes
This is a good start but there are some needed adjustments.  Also, make sure your local development environment is set up to build the C# code locally so you can catch compile-time errors ASAP.

2024-03-13 14:57 UTC, cfarmer-fearless commented on upload-configs/allowed_data_stream.json
> +[
I would like this information to be part of the `copy config` in the partner-specific json files

2024-03-13 14:57 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +        private readonly string _dataStreamFileName = "allowed_data_stream.json";
I think we just want to load the single upload config file moving forward.

2024-03-13 16:11 UTC, USZ7 commented on upload-configs/README.md
> +1. Create a file for the desination_id and ext_event with the format: ```{destination_id}-{ext_event}.json```. For example, "```ndlp-routineImmunization.json```".
Shouldn't it be "data_stream_id" and "ext_data_stream_route"?

2024-03-14 18:30 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            _uploadConfigsFolder = Environment.GetEnvironmentVariable("UPLOAD_CONFIGS_FOLDER", EnvironmentVariableTarget.Process) ?? "";
It's not.  It's stored as an app config setting on the function app instance.

2024-03-14 18:35 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +CONFIG_FILES = ['../../../upload-configs/v1/aims-celr-csv.json', '../../../upload-configs/v1/aims-celr-hl7.json', '../../../upload-configs/v1/daart-hl7.json',
These files need to be read in from where they will live in Azure storage, not from a local file system.  Additionally, we don't need to hard code all of them like this.  We can programmatically create these filenames using the destination and event metadata fields passed in the metadata.

2024-03-15 17:23 UTC, USZ7 commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +def verify_allowed_data_stream(dest_id, event_type):
This method needs an additional parameter, 'meta_json', since the code on line 226 calls it with three parameters

2024-03-18 14:24 UTC, cfarmer-fearless requested changes

2024-03-18 14:24 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +        upload_config_file = f"{metadata['meta_destination_id']}-{metadata['meta_ext_event']}.json"
This file does not exist in the tus container's file system.  It exists in a storage container and will need to be retrieved from there.

2024-03-18 14:24 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +def verify_allowed_data_stream(dest_id, event_type, metadata):
Perhaps we don't need to pass in all of these arguments to this function.

2024-03-18 14:24 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +            definitions = file.read()
We can probably rename `definitions` to `upload_config`

2024-03-18 14:24 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/test/test_allowed_data_stream.py
> +    @patch('builtins.open', new_callable=mock_open, read_data='[{"destination_id": "dest_one", "ext_events": [{"name": "event_one", "definition_filename": "definition_one.json"}]}]')
You'll most likely need to mock an azure blob client instead of `builtins.open`

2024-03-18 14:24 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/test/test_allowed_data_stream.py
> +    def test_verify_allowed_data_stream_missing_metadata(self, mock_file_open):
Is this test already covered in `test_required_metadata.py`?

2024-03-18 14:24 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/test/test_required_metadata.py
> +    def test_missing_metadata_data_strean_id(self):
I don't think we should be changing these tests for the v2 fields yet.  We should still be testing the v1 fields.

2024-03-18 14:24 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> -        private async Task<List<DestinationAndEvents>?>  GetAllDestinationAndEvents()
This function app still needs to get all destinations and events for a file.  We don't want to totally eliminate that functionality.  We only want to change the source of where it gets that information.

2024-03-18 14:24 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
>          private readonly string _tusHooksFolder;
This class will also need to be refactored to fetch and deserialize the upload config json file for a given file.  It will need to pull the copy config and copy targets from that json file.

2024-03-20 11:45 UTC, cfarmer-fearless requested changes
A few minor corrections.  But looks like there is still some refactoring to do in pre-create and UploadProcessingService

2024-03-20 11:45 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +TUS_AZURE_STORAGE_CONTAINER = os.getenv('TUS_AZURE_STORAGE_CONTAINER')
I don't think this environment variable is currently set in the tus app service.  Do we need to add it?  What value is it supposed to take on?

2024-03-20 11:45 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +        blob_client = DEX_STORAGE_ACCOUNT_SERVICE.get_blob_client(container=UPLOAD_CONFIG, blob=upload_config_file)
Make sure the `container` parameter in `get_blob_client` is set to "upload-configs" because that's the name of the container holding all of the upload configs.

2024-03-20 11:45 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +        raise Exception(failure_message) from e
What does the `from e` statement do?

2024-03-20 11:45 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/test/test_upload_config.py
> +class TestUploadConfig(unittest.TestCase):
These are solid unit tests.  Well done

2024-03-20 11:45 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            var configFilename = $"{destinationId}-{eventType}.json";
`configFilename = null-null.json`?

2024-03-20 11:45 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                destinationAndEvents = await _blobReader.GetObjectFromBlobJsonContent<List<DestinationAndEvents>>(_dexStorageAccountConnectionString, _tusHooksFolder, configFilename);
The upload config lives in the `upload-configs` container, not the `_tusHooksFolder` container

2024-03-20 11:45 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
>          private async Task<List<DestinationAndEvents>?>  GetAllDestinationAndEvents()
I may have been incorrect in my last comment.  This might not be needed actually.  Let's discuss.

2024-03-22 18:00 UTC, cfarmer-fearless approved these changes

2024-03-22 18:03 UTC, merged