Dex file copy 1054
CDCgov/data-exchange-upload pull request #264
Opened 2024-03-19 18:57 UTC by gulnaz-cdc

testNG configuration for dex file copy and Meta data verify parameterization for all use cases

2024-03-19 21:37 UTC, cfarmer-fearless requested changes

2024-03-19 21:37 UTC, cfarmer-fearless commented on tests/integration/kotlin/src/test/kotlin/util/Metadata.kt
> +        fun generateRequiredMetadataForFile(file: File, propertiesFilePath: String): HashMap<String, String> {
The `file` parameter is unused here and can be removed

2024-03-19 21:37 UTC, cfarmer-fearless commented on tests/integration/kotlin/src/test/resources/properties/daart-hl7.properties
> +#original_file_timestamp=timestampvalue
Remove commented property

2024-03-19 21:37 UTC, cfarmer-fearless commented on tests/integration/kotlin/src/test/resources/properties/dex-hl7-hl7ingress.properties
> +#message_type=ELR
Remove commented property

2024-03-19 21:37 UTC, cfarmer-fearless commented on tests/integration/kotlin/src/test/resources/properties/ndlp-routineimmunization.properties
> +#meta_ext_sourceversion=["V2022-12-31","V2023-09-01"]
Remove commented property

2024-03-19 21:37 UTC, cfarmer-fearless commented on tests/integration/kotlin/src/test/resources/testNG.xml
> +<!--            <class name="ProcStat">-->
We should be able to keep all test classes commented in, and provide documentation on how to run all of them at once, and run only a specific one.

2024-03-19 21:37 UTC, cfarmer-fearless commented on tests/integration/kotlin/src/test/kotlin/util/Utilities.kt
> +    fun extractMetadataFromResponseBody(jsonResponse: String): HashMap<String, String> {
This function can likely be removed if it's not needed after removing the proc stat code from `MetadataVerify.kt`.

2024-03-21 13:31 UTC, gulnaz-cdc commented on tests/integration/kotlin/src/test/resources/properties/dex-hl7-hl7ingress.properties
> +#message_type=ELR
there are two types of message_type CASE and ELR, we can do one at a time, this is for convenience. If a user wants to switch to the mrssage_type=ELR,  the user simply can comment out the first message type.

2024-03-22 17:36 UTC, cfarmer-fearless approved these changes

2024-03-22 17:36 UTC, merged