Upload-811: support both v1 and v2 metadata
CDCgov/data-exchange-upload pull request #270
Opened 2024-03-26 19:05 UTC by dancing-goats

This PR refactors the following TUS hooks to validate v2 metadata that supports v2 metadata model:

- pre-create
- post-create
- post-receive

The UploadProcessing service has been refactored to hydrate V1 metadata. 

link: https://cdc-dexops.atlassian.net/browse/UPLOAD-811

2024-03-26 21:35 UTC, USZ7 commented on tus/file-hooks/post-create/post_create_bin.py
> +    if metadata_version == "2.0":
It would be more maintainable to define the hardcoded values like (metadata_version) as constants at the top. 
This makes it easier to update and manage the versions and associated fields.

2024-03-26 21:55 UTC, cfarmer-fearless requested changes
See comments.  Some corrections to make.  You also need to

- Remove the hard-coded v1 in `get_upload_config` for `pre_create_bin.py`
- Perform a similar version check in the C# code.

2024-03-26 21:55 UTC, cfarmer-fearless commented on tus/file-hooks/post-create/test/test_post_create.py
> -  @patch.object(ProcStatController, 'create_upload_trace', return_value=("trace_id", "parent_span_id"))
What's the purpose of these changes?  Just formatting?

2024-03-27 19:42 UTC, cfarmer-fearless requested changes

2024-03-27 19:42 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +        upload_config_file = f"{dest_id}-{event_type}.json"
You still need to prepend the version number to `upload_config_file`.  You can't just remove it.  It just needs to by dynamic to the version number that is in the sender manifest.

2024-03-27 19:42 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +    if metadata_version == METADATA_VERSION_ONE:
switch these conditions.  `data_stream_id` and `data_stream_route` are v2 fields.

2024-03-27 19:42 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +        required_fields = ['data_stream_id', 'data_stream_route']
I still think these `required_fields` arrays can be global constants.

2024-03-27 19:42 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
> +    if metadata_version == METADATA_VERSION_ONE:
Again, `data_stream_id` and `data_stream_route` are v2 fields.

2024-03-28 19:03 UTC, cfarmer-fearless requested changes

2024-03-28 19:03 UTC, cfarmer-fearless commented on tus/file-hooks/upload-status/post_receive_bin.py
> +        json_data, metadata_version = await process_metadata_version(metadata, filename, tguid, offset, size, metadata_json_dict)
Make `process_metadata_version` synchronous and remove the `await`.

2024-03-28 19:03 UTC, cfarmer-fearless commented on tus/file-hooks/upload-status/post_receive_bin.py
> +        data_stream_id = metadata.data_stream_id
Are these `data_stream_id` and `data_stream_route` variables necessary?

2024-03-28 19:03 UTC, cfarmer-fearless commented on tus/file-hooks/upload-status/post_receive_bin.py
> +        meta_destination_id = metadata.meta_destination_id
Are the `meta_destination_id` and `meta_ext_event` variables necessary?

2024-03-28 19:07 UTC, cfarmer-fearless requested changes

2024-03-28 19:07 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                    throw new TusInfoFileException("version is a required metadata field and is missing from the tus info file");
The version is not a required metadata field.  If it's not provided, we will default to "1.0"

2024-03-28 19:07 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                if (metadataVersion == metadataVersionOne)
A lot of duplicate code here.  The only thing we need to conditionally do is hydrate metadata.

2024-03-28 20:37 UTC, dancing-goats commented on tus/file-hooks/upload-status/post_receive_bin.py
> +        data_stream_id = metadata.data_stream_id
Yes, they are needed to construct the json_data dictionary based on the metadata version.

2024-03-29 13:38 UTC, cfarmer-fearless requested changes

2024-03-29 13:38 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/pre_create_bin.py
>      upload_config = get_upload_config(dest_id, event_type)
Looks like `get_upload_config` still takes the version as a third argument.  Did you mean to remove that in your last commit?

2024-03-29 13:38 UTC, cfarmer-fearless commented on tus/file-hooks/metadata-verify/test/test_get_required_metadata.py
> +    def test_missing_required_fields(self):
Please include a test for v2 required metadata field here as well.

2024-03-29 13:38 UTC, cfarmer-fearless commented on tus/file-hooks/post-create/post_create_bin.py
> +    metadata_version = metadata_json_dict['metadata_config']['version']
`metadata_json_dict` will be the sender manifest, not the upload config.  It will not have a `metadata_config` key.

2024-03-29 13:38 UTC, cfarmer-fearless commented on tus/file-hooks/post-create/post_create_bin.py
> +    if missing_metadata_fields:
Why change this condition?

2024-03-29 13:38 UTC, cfarmer-fearless commented on tus/file-hooks/post-create/test/test_post_create.py
> +            'metadata_config': {
`metadata_config` is not a fields in the sender manifest.

2024-03-29 13:43 UTC, cfarmer-fearless requested changes

2024-03-29 13:43 UTC, cfarmer-fearless commented on tus/file-hooks/upload-status/post_receive_bin.py
> +        logger.info('filename = {0}, metadata_version = {1}'.format(filename, metadata_version))
Looks like `metadata_version` is undefined here.  Looks like it's defined on line 81.

2024-03-29 13:43 UTC, cfarmer-fearless commented on tus/file-hooks/upload-status/post_receive_bin.py
> +    metadata_version = metadata.metadata_config.version
`metadata` is the sender manifest, not the upload config.

2024-03-29 13:43 UTC, cfarmer-fearless commented on tus/file-hooks/upload-status/test/test_post_receive.py
> +            "metadata_config": {"version": "2.0"},
This is not the upload config.

2024-03-29 13:43 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Model/MetadataVersion.cs
> +                case 1 when this == V1:
Is this valid syntax?

2024-04-01 21:40 UTC, cfarmer-fearless approved these changes

2024-04-01 21:45 UTC, merged