Upload 1103 reuse connections for blob service clients in upload processor
CDCgov/data-exchange-upload pull request #285
Opened 2024-04-05 19:07 UTC by tedtally

2024-04-08 20:44 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBlobServiceClientFactory.cs
> +    public class BlobServiceClientFactory : IBlobServiceClientFactory
Correct. That is definitely one way of ensuring a single instance but if you look at the implementation class, it shows how it returns the same instance by using the _instances.GetOrAdd method.

2024-04-23 17:35 UTC, USZ7 approved these changes
lgtm!

2024-04-23 17:36 UTC, cfarmer-fearless requested changes
Several places for cleanup, but the logic looks good.

2024-04-23 17:36 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Model/DestinationAndEvents.cs
> +﻿using System.Text.Json.Serialization;
This class isn't being used anymore and can be removed.

2024-04-23 17:36 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +using Azure.Identity;
Remove unused imports.

2024-04-23 17:36 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/JsonLoggerBase.cs
> +﻿// Default URL for triggering event grid function in the local environment.
What's the purpose of this?

2024-04-23 17:36 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/IJsonLoggerProvider.cs
> +﻿// Default URL for triggering event grid function in the local environment.
What's the purpose of this interface?

2024-04-23 17:36 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Utils/HealthCheckResultUtil.cs
> +            //HealthCheckResult? checkResult = null;
Remove commented code if it's unused.

2024-04-23 17:36 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Utils/HealthCheckResultUtil.cs
> +using Microsoft.Identity.Client.Platforms.Features.DesktopOs.Kerberos;
Remove unused imports

2024-04-24 13:03 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +using Azure.Identity;
I removed the unused imports. FYI, the ones you are highlighting are still being used

2024-04-24 13:18 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Utils/HealthCheckResultUtil.cs
> +using Microsoft.Identity.Client.Platforms.Features.DesktopOs.Kerberos;
done

2024-04-24 13:22 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/JsonLoggerBase.cs
> +﻿// Default URL for triggering event grid function in the local environment.
I am not familiar with this interface. This might be a result of a previous merge with main. This was probably created in an attempt perform unit testing

2024-04-24 13:25 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Model/DestinationAndEvents.cs
> +﻿using System.Text.Json.Serialization;
done

2024-04-24 18:59 UTC, cfarmer-fearless commented
Closing in favor of GoLang refactor.

2024-04-24 18:59 UTC, closed without merging