Upload recovery tool
CDCgov/data-exchange-upload pull request #334
Opened 2024-05-03 18:32 UTC by cfarmer-fearless

2024-05-06 13:43 UTC, USZ7 commented on reupload-tool/src/main/kotlin/Main.kt
> +    return File(object {}::class.java.classLoader.getResource(filename)?.file!!)
Where does the class loader get the input.csv file from?

2024-05-06 20:31 UTC, cfarmer-fearless commented on reupload-tool/src/main/kotlin/Main.kt
> +    return File(object {}::class.java.classLoader.getResource(filename)?.file!!)
From the `resource` directory.

2024-05-07 13:49 UTC, whytheplatypus requested changes

2024-05-07 13:49 UTC, whytheplatypus commented on reupload-tool/src/main/kotlin/Main.kt
> +    val inputCsv = getFileFromResources("input.csv")
get this from input, probably a flag with this as a default.

2024-05-07 13:49 UTC, whytheplatypus commented on reupload-tool/src/main/kotlin/Main.kt
> +    val authToken = authClient.getToken(EnvConfig.SAMS_USERNAME, EnvConfig.SAMS_PASSWORD)
provide a way to skip auth

2024-05-07 13:49 UTC, whytheplatypus commented on reupload-tool/src/main/kotlin/Main.kt
> +            uploadClient.uploadFile(fileToUpload, updatedMetadata)
suggestion: extract this and have it return a `Result`

2024-05-22 21:05 UTC, cfarmer-fearless commented on reupload-tool/src/main/kotlin/Main.kt
> +    val inputCsv = getFileFromResources("input.csv")
Done.  Used Java system args for compatibility.

2024-05-22 21:19 UTC, cfarmer-fearless commented on reupload-tool/src/main/kotlin/Main.kt
> +    val authToken = authClient.getToken(EnvConfig.SAMS_USERNAME, EnvConfig.SAMS_PASSWORD)
Added a flag

2024-05-22 21:32 UTC, cfarmer-fearless commented on reupload-tool/src/main/kotlin/Main.kt
> +            uploadClient.uploadFile(fileToUpload, updatedMetadata)
Done

2024-08-28 14:45 UTC, cfarmer-fearless commented
Closing in favor of https://github.com/CDCgov/data-exchange-upload/pull/464

2024-08-28 14:45 UTC, closed without merging