Deprecate trace calls from PS API to service bus
CDCgov/data-exchange-upload pull request #335
Opened 2024-05-06 21:03 UTC by tedtally

2024-05-07 12:47 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> -            try
Any real changes here or just formatting?

2024-05-07 12:48 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                // TODO: refactor to use service bus instead
Same thing here: we don't care about spans anymore, just like we don't care about trace anymore.  It can be removed.

2024-05-09 20:56 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                // TODO: refactor to use service bus instead
done

2024-05-09 20:56 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Utils/Constants.cs
> +        public const string PROC_STAT_FEATURE_FLAG_NAME = "PROCESSING_STATUS_TRACES"; // disable this feature flag to stop sending processing status traces
thanks. done

2024-05-10 16:11 UTC, dancing-goats reviewed
Nice work, just had some clarifying questions in the comments.

2024-05-10 16:11 UTC, dancing-goats commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +            {               // TODO: remove
Do you need this TODO comment?

2024-05-10 16:11 UTC, dancing-goats commented on upload-processor/BulkFileUploadFunctionApp/Utils/Constants.cs
> +        public const string SERVICE_BUS_CONNECTION_STR = "https://onceler.app.cloud.gov/once/gsneqjqorweo4cvwdrf5jayh2hgzf9/";
Should `https://onceler.app.cloud.gov/once/gsneqjqorweo4cvwdrf5jayh2hgzf9/` be committed to code? Is it a private internal link?

2024-05-10 17:18 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Utils/Constants.cs
> +        public const string SERVICE_BUS_CONNECTION_STR = "https://onceler.app.cloud.gov/once/gsneqjqorweo4cvwdrf5jayh2hgzf9/";
onceler is a tool used to share secrets securely.  You are meant to open the link in a browser and get the secret within.  In this case, the secret is the connection string.

2024-05-10 18:03 UTC, cfarmer-fearless requested changes
The overall approach is sound.  There's just a lot of cleanup that can be done.

2024-05-10 18:03 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                await _featureManagementExecutor.ExecuteIfEnabledAsync(Constants.PROCESSING_STATUS_REPORTS_FLAG_NAME, async () =>
`SendFailureReport` and `SendSuccessReport` already check the feature flag, so you don't need to check it here twice.

2024-05-10 18:03 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Utils/Constants.cs
> +        public const string SERVICE_BUS_CONNECTION_STR = "https://onceler.app.cloud.gov/once/gsneqjqorweo4cvwdrf5jayh2hgzf9/";
The connection string needs to come from the environment variables.  Hardcoding it as a constant here would be very bad as this is a public repo and it's a security sensative value.

2024-05-10 18:03 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/HealthCheckFunctionTests.cs
> +            //_procStatClientMock.Setup(mock => mock.GetHealthCheck()).Returns(Task.FromResult(TestHelpers.CreateUpResponse()));
Remove commented code.

2024-05-10 18:35 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Utils/Constants.cs
> +        public const string SERVICE_BUS_CONNECTION_STR = "https://onceler.app.cloud.gov/once/gsneqjqorweo4cvwdrf5jayh2hgzf9/";
Correct. That should not have been in the code. I have removed the constant from the codebase and the link has been expired.

2024-05-10 19:14 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Program.cs
> +        // TODO: Register the ServiceBusClient as a singleton.
done

2024-05-10 19:21 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +        Task<bool> CreateReport<TReport>(string uploadId, string destinationId, string eventType, string stageName, TReport payload);
Makes sense. Done.

2024-05-10 20:16 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +            var serviceBusAdministrationClient = new ServiceBusAdministrationClient(_serviceBusConnectionString);
refactored and done.

2024-05-10 20:18 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +        private string GetFilenameSuffix(UploadConfig uploadConfig, string uploadId)
correct.

2024-05-10 21:52 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            if (uploadConfig.CopyConfig?.FilenameSuffix == CopyConfig.FILENAME_SIFFIX_UID)
done

2024-05-11 23:21 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                await _featureManagementExecutor.ExecuteIfEnabledAsync(Constants.PROCESSING_STATUS_REPORTS_FLAG_NAME, async () =>
done

2024-05-11 23:22 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Utils/Constants.cs
> +        public const string SERVICE_BUS_CONNECTION_STR = "https://onceler.app.cloud.gov/once/gsneqjqorweo4cvwdrf5jayh2hgzf9/";
I removed the constant and the link.

2024-05-11 23:34 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +                   var responseBody = await DoesQueueExistAsync(_serviceBusQueueName);
done

2024-05-11 23:39 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +            {               // TODO: remove
done

2024-05-13 14:43 UTC, cfarmer-fearless requested changes
- Instantiate svc bus client in upload service constructor instead of singleton.
- Remove svc bus receiver
- Better exception handling of queue exist
- publish to return Task<void>.  Optional retry on ServiceBusException.
- Publish to not have template type.  Payload param to be of type Report.

2024-05-13 16:23 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Program.cs
> +        services.AddSingleton<IBulkUploadSvcBusClient, BulkUploadSvcBusClient>();
Per our discussion, I will pass the connection string and queue inside the UploadprocessingService.cs instead.

2024-05-13 17:32 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Program.cs
> +        services.AddSingleton<IBulkUploadSvcBusClient, BulkUploadSvcBusClient>();
done

2024-05-13 18:56 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +        public async Task<bool> DoesQueueExistAsync(string queueName)
good point. done.

2024-05-13 22:08 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/ProcStatClient.cs
>              return true;
done

2024-05-13 22:09 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +        private readonly ServiceBusSender _serviceBusSender;
removed

2024-05-14 13:00 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +        Task<bool> CreateReport<TReport>(string uploadId, string destinationId, string eventType, string stageName, TReport payload);
done.

2024-05-14 13:01 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +        Task<bool> CreateReport<TReport>(string uploadId, string destinationId, string eventType, string stageName, TReport payload);
changed the function to a void

2024-05-14 17:28 UTC, cfarmer-fearless requested changes
More cleanup

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
> +                                    IBulkUploadSvcBusClient bulkUploadSvcBusClient)
Instantiate in constructor instead of dependency inject.

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Program.cs
> +        services.AddSingleton<IBulkUploadSvcBusClient, BulkUploadSvcBusClient>();
Remove this singleton

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +                await Task.Delay(1000); // 1 second delay before retrying
Not sure where the actual retry is happening.  If you aren't retrying, please remove this delay as it's unnecessary

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +            var serviceBusAdministrationClient = new ServiceBusAdministrationClient(_serviceBusConnectionString);
This is still incomplete

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +        public void PublishReport(string uploadId, string destinationId, string eventType, string stageName, Report payload)
This can still return a `Task`

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +                    if (currentRetryAttempt >= maxRetryAttempts)
I don't think you need this check since the `while` loop is covering this

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +using System.Runtime.Intrinsics.X86;
Remove unused imports

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +        public UploadProcessingService(ILoggerFactory loggerFactory, IBulkUploadSvcBusClient bulkUploadSvcBusClient,
Remove dependency injection for svc bus client

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            _bulkUploadSvcBusClient = new BulkUploadSvcBusClient(_ServiceBusConnectionString, _ServiceBusQueueName, loggerFactory.CreateLogger<BulkUploadSvcBusClient>());
Use `_logger` instead of creating a new logger

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                catch(System.Runtime.Serialization.SerializationException se)
These specific exceptions are already being handled and logged within `PublishReport`.  If all you're doing here is logging again, catching is unnecessary.

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            _ServiceBusQueueName = Environment.GetEnvironmentVariable("REPORT_QUEUE_NAME", EnvironmentVariableTarget.Process) ?? "";
Default to the constant `REPORT_QUEUE_NAME` that you created

2024-05-14 17:28 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            _mockServiceBusAdministrationClient = new Mock<ServiceBusAdministrationClient>();
What's the point of this mock?  Looks like it isn't being used.

2024-05-14 17:31 UTC, cfarmer-fearless requested changes
Tweaks to retry logic

2024-05-14 17:31 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +                    throw;
Break instead of throw

2024-05-14 17:31 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +                    throw;
Break instead of throw

2024-05-16 20:18 UTC, cfarmer-fearless approved these changes

2024-05-16 20:22 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionTests.cs
> +            _mockServiceBusAdministrationClient = new Mock<ServiceBusAdministrationClient>();
It's not anymore. I will remove it.

2024-05-16 20:24 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Program.cs
> +        services.AddSingleton<IBulkUploadSvcBusClient, BulkUploadSvcBusClient>();
done

2024-05-16 20:31 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +                await Task.Delay(1000); // 1 second delay before retrying
done

2024-05-16 20:33 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +        public void PublishReport(string uploadId, string destinationId, string eventType, string stageName, Report payload)
I moved the serviceBusAdministrationClient variable into the constructor and changed the PublishReport return type back to Task

2024-05-16 20:49 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            _bulkUploadSvcBusClient = new BulkUploadSvcBusClient(_ServiceBusConnectionString, _ServiceBusQueueName, loggerFactory.CreateLogger<BulkUploadSvcBusClient>());
deprecated

2024-05-16 21:15 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +            _ServiceBusQueueName = Environment.GetEnvironmentVariable("REPORT_QUEUE_NAME", EnvironmentVariableTarget.Process) ?? "";
done

2024-05-16 21:32 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +                catch(System.Runtime.Serialization.SerializationException se)
removed

2024-05-16 21:33 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +                    throw;
no longer applicable since this code is no longer in a while loop

2024-05-16 21:34 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +                    throw;
while loop has been deprecated

2024-05-16 21:34 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +        public void PublishReport(string uploadId, string destinationId, string eventType, string stageName, Report payload)
done

2024-05-16 21:35 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +                    if (currentRetryAttempt >= maxRetryAttempts)
while loop has been deprecated

2024-05-16 21:35 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
> +using System.Runtime.Intrinsics.X86;
done

2024-05-16 21:39 UTC, tedtally commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
> +            var serviceBusAdministrationClient = new ServiceBusAdministrationClient(_serviceBusConnectionString);
move it to the service bus client constructor as an instance variable _serviceBusAdministrationClient

2024-05-17 15:52 UTC, merged