Added a function for Smoke test for v1 to v2 metadata translation
CDCgov/data-exchange-upload pull request #336
Opened 2024-05-06 22:22 UTC by GSA2024

2024-05-07 11:54 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    fun verifyMetadataTranslation(){
I like to use more descriptive test function names.  Like `shouldTranslateMetadataGivenV1SenderManifest`.

2024-05-07 11:54 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +            assert(routingUploadBlob.metadata?.containsKey(key) == true) {"Metadata key '$key' not found"}
It isn't clear what this test is actually verifying.  It looks like you are getting a set of metadata keys from the blob, and then checking is those keys exist in the same blob.  Won't that always be true?  Is this just an initial setup for getting the blob?

2024-05-07 11:54 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        val routingUploadBlob =routingContainerClient.listBlobs(options, Duration.ofMillis(EnvConfig.AZURE_BLOB_SEARCH_DURATION_MILLIS))
You should be able to create a blob client to the file directly instead of using `listBlobs` to search the container.

2024-05-07 19:25 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    fun verifyMetadataTranslation(){
Updated function name

2024-05-07 19:27 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        val routingUploadBlob =routingContainerClient.listBlobs(options, Duration.ofMillis(EnvConfig.AZURE_BLOB_SEARCH_DURATION_MILLIS))
Accessing blob client for the file directly, rather than `listBlobs`

2024-05-09 12:23 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +            assert(routingUploadBlob.metadata?.containsKey(key) == true) {"Metadata key '$key' not found"}
Updated assertions that can validate metadata vs v1 property file

2024-05-09 12:30 UTC, cfarmer-fearless requested changes
It still isn't clear where the test is checking for the v2 fields, like `data_stream_id` and `data_stream_route`.

2024-05-09 12:30 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        println("Storing Metadata")
Please remove any debug logs before merging.

2024-05-09 12:30 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +                Assert.assertEquals(value, expectedValue,  "Mismatch for key: $key")
Where is this checking for the v2 fields?

2024-05-09 23:00 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +                Assert.assertEquals(value, expectedValue,  "Mismatch for key: $key")
Updated based on all review comments.

1.	Created a new property file dextesting-testevent1-mapping.properties. This file has mappings of keys from V1 to V2, which will help to compare corresponding fields in the blob metadata.
2.	A test shouldTranslateMetadataGivenV1SenderManifsest ha a couple of validations below,
a.	Metadata Value Validation – this checks if the metadata values from the version (V1) match the version (V2) of blob metadata after transformation.
b.	Metadata Key Validation - this checks that each key from the version (V2) is actually present in the blob metadata.

2024-05-09 23:08 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        println("Storing Metadata")
Removed debug logs

2024-05-10 17:13 UTC, cfarmer-fearless requested changes

2024-05-10 17:13 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/Constants.kt
> +        const val DEX_UPLOAD_CONTAINER_NAME = "dextesting-testevent1"
The container name is based on use case.  We can't hard code it.

2024-05-10 17:13 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/tst/dextesting-testevent1.xml
> +        <parameter name="SENDER_MANIFEST_MAPPING" value="dextesting-testevent1-mapping.properties"/>
I'm not a fan of this approach.  The mappings are already defined in the upload configs.  We should just use them so we don't have to keep another set of files up to date.

2024-05-13 15:16 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/tst/dextesting-testevent1.xml
> +        <parameter name="SENDER_MANIFEST_MAPPING" value="dextesting-testevent1-mapping.properties"/>
Approach have been changed as below,

1. shouldTranslateMetadataGivenV2SenderManifest: Updated this test for reading the data from the V2 JSON file
2. Created a separate function"loadUploadConfig" in ConfigLoader.kt file to call V1 and V2 JSON files dynamically
3. Created a new "ConfigLoader" class in the "model" package for loading and preprocessing configuration data from a JSON files
4. Updated "UploadConfig" class for metadata_config from JSON file
5. Created a new "MetadataConfig" class in the "model" package to access configuration details for metadata versions and fields settings
6. Created a new "FieldConfig" class in the "model" package for mapping field_name and compat_field_name

2024-05-13 16:39 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        val blobProperties = expectedBlobClient?.properties
This is updated

2024-05-13 17:53 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/Constants.kt
> +        const val DEX_UPLOAD_CONTAINER_NAME = "dextesting-testevent1"
DEX_UPLOAD_CONTAINER_NAME has been removed and used usecase instead

2024-05-13 19:33 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        val expectedFilename = "${Metadata.getFilePrefixByDate(DateTime(DateTimeZone.UTC), useCase)}/${testFile.nameWithoutExtension}$filenameSuffix.${testFile.extension}"
method overloaded by removing useCase.

2024-05-13 20:15 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        val filenameSuffix = if (uploadConfig.copyConfig.filenameSuffix == "upload_id") "_${uploadId}" else ""
created a utility file.

2024-05-14 17:08 UTC, cfarmer-fearless requested changes
Test looks good overall, just some final cleanup needed.

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        //val filenameSuffix = if (uploadConfigV1.copyConfig.filenameSuffix == "upload_id") "_${uploadId}" else ""
Remove commented code.

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        //val filenameSuffix = if (uploadConfigV1.copyConfig.filenameSuffix == "upload_id") "_${uploadId}" else ""
Remove commented code

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/model/ConfigLoader.kt
> +package model
Please move to `util` package.  The `model` package is for data classes only.

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/model/ConfigLoader.kt
> +    fun loadUploadConfig(dexBlobClient: BlobServiceClient, useCase: String, version: String): UploadConfig {
Make this a static function since it doesn't depend on any internal state.

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/model/CopyConfig.kt
> +import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
Remove unused imports

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/tus/UploadClient.kt
> +import com.azure.storage.blob.models.BlobItem
Remove unused imports

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/properties/dextesting-testevent1/dextesting-testevent1-mapping.properties
> +# # V1 to V2 Metadata Mappings
Remove

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/properties/dextesting-testevent1/dextesting-testevent1.properties
> +# V2
Remove commented code

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/tst/dextesting-testevent1.xml
> +      <parameter name="USE_CASE" value="dextesting-testevent1" />
Fix spacing

2024-05-14 17:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +import java.io.FileInputStream
Remove unused imports

2024-05-14 19:42 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    fun shouldTranslateMetadataGivenV2SenderManifest() {
Updated to shouldTranslateMetadataGivenV1SenderManifest

2024-05-14 19:44 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        //val filenameSuffix = if (uploadConfigV1.copyConfig.filenameSuffix == "upload_id") "_${uploadId}" else ""
Removed commented code

2024-05-14 19:44 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        //val filenameSuffix = if (uploadConfigV1.copyConfig.filenameSuffix == "upload_id") "_${uploadId}" else ""
Removed commented code

2024-05-14 19:48 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> -        context.setAttribute("uploadId", uploadId)
set attribute upload id is not removed

2024-05-14 19:50 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/dextesting-testevent1/dextesting-testevent1-mapping.properties
> +# # V1 to V2 Metadata Mappings
Removed

2024-05-14 19:50 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/dextesting-testevent1/dextesting-testevent1.properties
> +# V2
Cleaned up

2024-05-14 19:51 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/tst/dextesting-testevent1.xml
> +      <parameter name="USE_CASE" value="dextesting-testevent1" />
Cleaned up

2024-05-14 19:51 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +import java.io.FileInputStream
Removed

2024-05-16 11:20 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/tus/UploadClient.kt
> +import com.azure.storage.blob.models.BlobItem
Done

2024-05-16 13:12 UTC, cfarmer-fearless requested changes

2024-05-16 13:12 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    fun shouldValidateV2MetadataWithSenderManifest() {
Move to 1248 PR

2024-05-16 15:49 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/V2/aims-celr-csv/aims-celr-csv.properties
> +#v2
All v2 sender manifest moved to 1248 branch

2024-05-16 15:59 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    @Parameters("SENDER_MANIFEST", "USE_CASE", "USE_CASEV2")
moved to another PR

2024-05-16 16:00 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    fun shouldValidateV2MetadataWithSenderManifest() {
this function moved to 1248 and removed in 1250 PR

2024-05-16 16:14 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        val filenameSuffix = if (uploadConfig.copyConfig.filenameSuffix == "upload_id") "_${uploadId}" else ""
Moved to utility file

2024-05-16 16:15 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/model/ConfigLoader.kt
> +package model
Config loader moved to `util` package

2024-05-16 16:16 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/model/ConfigLoader.kt
> +    fun loadUploadConfig(dexBlobClient: BlobServiceClient, useCase: String, version: String): UploadConfig {
Made as a static function

2024-05-16 16:16 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/model/CopyConfig.kt
> +import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
Removed all unused imports

2024-05-16 18:37 UTC, cfarmer-fearless approved these changes

2024-05-16 18:45 UTC, merged