Upload 1200/report improvements
CDCgov/data-exchange-upload pull request #357
Opened 2024-05-15 21:20 UTC by cfarmer-fearless

2024-05-20 19:07 UTC, tedtally commented on upload-server/internal/metadata/metadata.go
> +		ReportContent: models.ReportContent{
Are we using camel case in Go?

2024-05-20 19:39 UTC, cfarmer-fearless commented on upload-processor/BulkFileUploadFunctionApp/Services/IBulkUploadSvcBusClient.cs
Which line are you referring to?

2024-05-20 19:39 UTC, cfarmer-fearless commented on upload-server/internal/metadata/metadata.go
> +		ReportContent: models.ReportContent{
Struct names are capital case in Go

2024-05-22 13:38 UTC, whytheplatypus requested changes
we need to be able to differentiate the stage an event is happening in. In this case the transform reports from the processor and the upload stages look the same. Can we use stage name to consistently say what step in the process this is in? Or add a new field for now like `service` so we know which one sent it out?

2024-05-22 18:22 UTC, cfarmer-fearless commented
Created follow on ticket for this work: https://cdc-dexops.atlassian.net/browse/UPLOAD-1352

2024-05-22 18:25 UTC, whytheplatypus approved these changes

2024-05-22 18:25 UTC, merged