v2 sender manifest validations
CDCgov/data-exchange-upload pull request #359
Opened 2024-05-17 12:40 UTC by GSA2024

2024-05-17 15:55 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    fun shouldValidateV2MetadataWithSenderManifest() {
This test does not belong in the `FileCopy` tests.  Only the `MetadataVerify` tests.

2024-05-17 15:57 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +    fun shouldUploadFileGivenRequiredMetadataV2(context: ITestContext) {
Is it possible to parameterize the manifest version?  That way we can reuse the tests we already have instead of make new ones.

2024-05-17 15:57 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/properties/V2/aims-celr-csv/aims-celr-csv.properties
> +sender_id=APHL
These manifests must set the `version` field to `2.0`.

2024-05-20 16:56 UTC, cfarmer-fearless requested changes

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    private lateinit var metadataV2: HashMap<String, String>
These changes appear to be unnecessary.  Please remove of so.

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +import com.azure.storage.blob.models.BlobStorageException
Remove unused import

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        this.useCase = USE_CASE
Remove unnecessary `this`

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        val uploadId: String? = if (version == "V1") {
if statement in unnecessary

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        if (version == "V1") {
if statement is unnecessary

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        if (version == "V1") {
if statement is unnecessary

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        if (version == "V1") {
if statement is unnecessary

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +    @Test(groups = [Constants.Groups.METADATA_VERIFY], dataProvider = "versionProvider", dataProviderClass = Metadata::class)
This test should only be run for v1 manifest

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +       private fun getMetadataPath(version: String, useCase: String, manifest: String): String {
Fix formatting

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +       private fun getMetadataPath(version: String, useCase: String, manifest: String): String {
Move private function to bottom

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +                    "properties/$useCase/$manifest"
We should move v1 manifests into their own subdirectory as well.

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/properties/V2/ndlp-covidbridgevaccination/ndlp-covidbridgevaccination.properties
> +#jurisdiction=["AKA","ALA","ASA","AZA","ARA","CAA","CHA","COA","CTA","DEA","DCA","FMA","FLA","GAA","GUA","HIA","IDA","ILA","IAA","INA","KSA","KYA","LAA","MEA","MHA","MDA","MAA","MIA","MNA","MSA","MOA
Remove commented out code

2024-05-20 16:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +        fun versionProvider(): Array<Array<String>> {
Let's make a separate data providers class.

2024-05-22 15:24 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    fun shouldValidateV2MetadataWithSenderManifest() {
Test is moved to `MetadataVerify`

2024-05-22 15:26 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/V2/aims-celr-csv/aims-celr-csv.properties
> +sender_id=APHL
Added version 2.0 filed v2 sender manifest

2024-05-22 15:27 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +    private lateinit var metadataV2: HashMap<String, String>
Removed redundant code

2024-05-22 15:28 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +import com.azure.storage.blob.models.BlobStorageException
Removed unused import

2024-05-22 15:29 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        this.useCase = USE_CASE
Since we are using Data provider for parameterization this code is cleaned up

2024-05-22 15:30 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        val uploadId: String? = if (version == "V1") {
Done

2024-05-22 15:30 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        if (version == "V1") {
Cleaned up

2024-05-22 15:30 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +       private fun getMetadataPath(version: String, useCase: String, manifest: String): String {
Done

2024-05-22 19:32 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        this.useCase = USE_CASE
Removed this keyword

2024-05-22 19:36 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +       private fun getMetadataPath(version: String, useCase: String, manifest: String): String {
Private function is moved to bottom

2024-05-22 19:46 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +                    "properties/$useCase/$manifest"
v1 manifests moved to V1 subdirectory.

2024-05-22 19:48 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/V2/ndlp-covidbridgevaccination/ndlp-covidbridgevaccination.properties
> +#jurisdiction=["AKA","ALA","ASA","AZA","ARA","CAA","CHA","COA","CTA","DEA","DCA","FMA","FLA","GAA","GUA","HIA","IDA","ILA","IAA","INA","KSA","KYA","LAA","MEA","MHA","MDA","MAA","MIA","MNA","MSA","MOA
Comment removed

2024-05-22 19:59 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +        fun versionProvider(): Array<Array<String>> {
Created `DataProvider` class and placed in the `Util` directory

2024-05-22 21:49 UTC, cfarmer-fearless approved these changes
Much better.  See comments for some final cleanup

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        context.setAttribute("uploadId_$version", uploadId)
Don't need to append the version to the upload ID.  This will break the custom error logging.

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        metadata = Metadata.getMetadataMap(version, useCase, senderManifest)
Suggestion: rename to `Metadata.getSenderManifest`

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        Thread.sleep(500)
Is this sleep necessary?

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +            Assert.assertTrue(blobMetadata.containsKey(field.fieldName), "V2 keys mismatch: ${field.fieldName}")
Make failure message dynamic

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        metadataFields.forEach { field ->
This check won't always be true.  If a metadata field is optional, it might not exist in the blob metadata.  Makes me think that this check is not necessary since you are already checking if the metadata that was uploaded matches the metadata on the file.

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +                arrayOf("V1"),
Use lowercase "v" to be consistent with how these folders are named in Azure.

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +        fun getFilePrefixByDate(date: DateTime, useCaseDir: String): String {
Fix formatting in lines 28, 30, and 31.  Looks like an extra space character at the beginning of the line.

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +        fun versionProvider(): Array<Array<String>> {
I see the new class.  It looks good.  Please delete this method now.

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/properties/V1/aims-celr-csv/no-dest-id.properties
> +meta_ext_event=csv
Undo this change.  hl7 is correct for this file.

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/properties/V2/dex-hl7-hl7ingress/dex-hl7-hl7ingress.properties
> +#route=PHLIP_FLU
Remove commented lines.

2024-05-22 21:49 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/properties/V2/ndlp-influenzavaccination/ndlp-influenzavaccination.properties
> +#jurisdiction=["AKA","ALA","ASA","AZA","ARA","CAA","CHA","COA","CTA","DEA","DCA","FMA","FLA","GAA","GUA","HIA","IDA","ILA","IAA","INA","KSA","KYA","LAA","MEA","MHA","MDA","MAA","MIA","MNA","MSA","MOA
Remove commented lines in all properties files.

2024-05-22 21:56 UTC, cfarmer-fearless requested changes

2024-05-22 21:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/resources/properties/V2/pulsenet-other/pulsenet-localsequencefile.properties
> +data_stream_route=other
Should be `localsequencefile` instead of `other`.  And file should be renamed to `pulsenet-localsequencefile.properties`

2024-05-22 21:58 UTC, cfarmer-fearless commented
Tests are failing for the other use cases.  It's looking good for `dextesting-testevent1`.  This is ok for now.

2024-05-23 13:41 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +        fun versionProvider(): Array<Array<String>> {
Removed `data provider` method from `Metadata` class

2024-05-23 13:43 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        context.setAttribute("uploadId_$version", uploadId)
Version is deleted from upload ID.

2024-05-23 13:45 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        metadata = Metadata.getMetadataMap(version, useCase, senderManifest)
Method name changed to `getSenderManifest`

2024-05-23 13:47 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        Thread.sleep(500)
Sleep is necessary otherwise getting an exception that blob was not found

2024-05-23 14:28 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +            Assert.assertTrue(blobMetadata.containsKey(field.fieldName), "V2 keys mismatch: ${field.fieldName}")
`metadataFields` block has removed, failure message is no longer present.

2024-05-23 14:28 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        metadataFields.forEach { field ->
Agree, checking `metadataFields` is not required to validate as `metadata` block is already verifying the values of metadata on the file.

2024-05-23 14:39 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +        fun getFilePrefixByDate(date: DateTime, useCaseDir: String): String {
Fixed formatting

2024-05-23 14:41 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/V2/ndlp-influenzavaccination/ndlp-influenzavaccination.properties
> +#jurisdiction=["AKA","ALA","ASA","AZA","ARA","CAA","CHA","COA","CTA","DEA","DCA","FMA","FLA","GAA","GUA","HIA","IDA","ILA","IAA","INA","KSA","KYA","LAA","MEA","MHA","MDA","MAA","MIA","MNA","MSA","MOA
Removed commented 'jurisdiction' on v2

2024-05-23 14:48 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/V1/aims-celr-csv/no-dest-id.properties
> +meta_ext_event=csv
Not sure, I have updated value to `hl7` as requested for v1 properties file for the filed `meta_ext_event`

2024-05-23 14:50 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/V2/dex-hl7-hl7ingress/dex-hl7-hl7ingress.properties
> +#route=PHLIP_FLU
Why do need to remove? We can test with different data for `message_type` and 'route`

2024-05-23 14:54 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/V2/pulsenet-other/pulsenet-localsequencefile.properties
> +data_stream_route=other
Updated to `localsequencefile`

2024-05-23 15:02 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/resources/properties/V2/dex-hl7-hl7ingress/dex-hl7-hl7ingress.properties
> +#route=PHLIP_FLU
Removed as requested

2024-05-23 15:12 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +                arrayOf("V1"),
Used lowercase 'v` for versions

2024-05-23 21:18 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        Thread.sleep(500)
Please add a comment saying the sleep is to wait for the uploaded test file to be routed to the destination storage container.

2024-05-23 21:19 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt
> +        fun getFilePrefixByDate(date: DateTime, useCaseDir: String): String {
Does not appear to be fixed.  I'm still seeing the space chars

2024-05-23 21:23 UTC, cfarmer-fearless requested changes
Added one new comment just a suggestion.  A few comments still not addressed.  Please made sure the diff shows the change.  Finally, rename the version directories to use lowercase "v".

2024-05-23 21:23 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        uploadConfigV1 = loadUploadConfig(dexBlobClient, USE_CASE, "v1")
Suggestion: see if you can add the version data provider to the `BeforeTest` function, that way you can make getting the upload config dynamic.

2024-05-24 00:30 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        Thread.sleep(500)
Added a comment for sleep message

2024-05-24 15:56 UTC, cfarmer-fearless requested changes
Look good but feel free to

2024-05-24 15:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        val uploadConfig = if (version == "V1") uploadConfigV1 else uploadConfigV2
Use "v1" instead of "V1"

2024-05-24 15:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/Info.kt
> +        val propertiesFilePath = "properties/V1/$USE_CASE/$senderManifestDataFile"
Use "v1" in path instead of "V1"

2024-05-24 15:56 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/FileCopy.kt
> +        val propertiesFilePath = "properties/V1/$USE_CASE/$senderManifestDataFile"
Use "v1" in path instead of "V1"

2024-05-24 22:01 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        if (version == "V1") {
This is updated.

2024-05-24 22:28 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +    @Test(groups = [Constants.Groups.METADATA_VERIFY], dataProvider = "versionProvider", dataProviderClass = Metadata::class)
This test works for both v1 and v2 with the `DataProvider`

2024-05-24 22:34 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/MetadataVerify.kt
> +        uploadConfigV1 = loadUploadConfig(dexBlobClient, USE_CASE, "v1")
'uploadcongiv1' and `uploadconfigv2' moved to the method `shouldValidateMetadataWithSenderManifest` and made one statement to read versions dynamically from the `DataProvider`.

2024-05-24 22:54 UTC, GSA2024 commented
> Look good but feel free to implement suggestion in previous comment.

2024-05-27 13:00 UTC, cfarmer-fearless approved these changes

2024-05-27 13:30 UTC, merged