Delivery Connection Resiliance and Health Check
CDCgov/data-exchange-upload pull request #393
Opened 2024-06-14 01:47 UTC by cfarmer-fearless

2024-06-14 01:50 UTC, cfarmer-fearless commented
Currently, not sure if deliverer and health check registration should be at the serve level or hook level.

2024-06-18 17:27 UTC, dtisza1 requested changes
@cfarmer-fearless Just had a few changes/additions, if they make sense.

For local file system storage, the following empty files could be added so that the related directories exist:

uploads/dex/.gitkeep
uploads/edav/.gitkeep
uploads/routing/.gitkeep

I was able to test locally and the code looks good to me!

2024-06-18 17:27 UTC, dtisza1 commented on upload-server/cmd/cli/hooks.go
> +	}
@cfarmer-fearless  I think these lines should be moved inside the else block on line 105, since they are not used when `appConfig.AzureConnection != nil`. Also the `metadataAppender` related lines above that.

2024-06-18 19:12 UTC, cfarmer-fearless commented on upload-server/cmd/cli/hooks.go
> +	}
Done

2024-06-18 20:08 UTC, dtisza1 approved these changes
@cfarmer-fearless Those changes and the PR look great!

Is working as expected locally too.

2024-06-18 20:18 UTC, merged