UPLOAD-1420 Custom Event Grid Topic
CDCgov/data-exchange-upload pull request #412
Opened 2024-06-28 13:08 UTC by cfarmer-fearless

2024-06-28 16:04 UTC, whytheplatypus commented on upload-server/internal/postprocessing/merge.go
> +			})
so this is kinda cool because it's a command not an event.

2024-06-28 16:06 UTC, whytheplatypus commented on upload-server/internal/postprocessing/postprocessor.go
> +	Process(ctx context.Context, event event.FileReadyEvent)
can separate these, i think?

2024-07-02 22:01 UTC, whytheplatypus requested changes
minor changes, looks great

2024-07-03 14:26 UTC, cfarmer-fearless commented on upload-server/cmd/main.go
> +	defer close(fileReadyChan)
I moved the channel to be internal to the event package.

2024-07-03 15:59 UTC, whytheplatypus approved these changes

2024-07-03 17:06 UTC, merged