Filter smoke tests by any manifest field
CDCgov/data-exchange-upload pull request #415
Opened 2024-07-01 13:40 UTC by GSA2024

Added Criteria Check that uses the all function to ensure that all key-value pairs in the criteria map match the corresponding values in the manifest (m)

- The function filters the list of manifests based on specified use cases and additional criteria.
- It constructs a useCase string from each manifest and checks if it is in the useCases list.
- It further filters the manifests based on the provided criteria map.

2024-07-02 14:08 UTC, cfarmer-fearless requested changes

2024-07-02 14:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +            val criteriaString: String? = System.getProperty("criteria")
These few lines for parsing the filter criteria are duplicated several times.  Good opportunity to put it in a function and reuse.

2024-07-02 14:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
>          private fun filterByUseCases(
Instead of filtering by use case, and then filtering by criteria, let's make this `filterByUseCases` a more generic filter function.  An simple approach is you can combine the `useCases` and `criteria` data, and it will just filter on criteria key value pairs.  This would eliminate the `useCases` command line argument.  I think in the end, this is what we want.  Just one command line argument for filtering manifests.

2024-07-02 14:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +            val criteriaString: String? = System.getProperty("criteria")
Suggestion: `manifestFilter` as a better name to `criteria`.

2024-07-02 14:08 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +                val (key, value) = it.split(":")
Make sure to update the README to explain how this new command line arg works.  Provide a few examples.

2024-07-02 17:31 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +            val criteriaString: String? = System.getProperty("criteria")
Updated name as `manifest filter` instead of `criteria`

2024-07-05 19:34 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +                val (key, value) = it.split(":")
README - WIP.
Run command line argument to run tests:
Ex: gradle test -PuseCases=meta_destination_id:ndlp,meta_ext_event:rsvprevention,meta_ext_entity:AKA

2024-07-09 13:14 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
>          private fun filterByUseCases(
`filterByUseCases` is a generic filter function that uses the combined filter criteria k/v pair one command line argument for filtering manifests.

2024-07-09 13:15 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +            val criteriaString: String? = System.getProperty("criteria")
Refactored the duplicated code in the data providers, created a common method that reads and filters the manifests based on the provided system properties. This will make the code more maintainable and concise.

2024-07-15 17:10 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +                    json[key]?.let { it in filterValues } ?: false
Deleted duplicated line

2024-07-15 19:30 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +            val pairs = manifestFilter?.split(";")
Renamed `pairs` to `fields`

2024-07-15 19:59 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +            if (pairs != null) {
Removed null check

2024-07-15 21:10 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
> +                    if (keyValue.size == 2) {
updated `parseFilterValues` function, if the values. Size is 1 (indicating no comma separator is present), it returns the single value as a list. If there are more than two elements, it throws an Exception. This way, we can handle both cases where there is no comma separator and where there is a single value without causing an error.

2024-07-15 21:53 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
>              return manifests.map { arrayOf(it) }.toTypedArray()
Added debug statement to print the number of filtered manifests against the size of the set of all manifests.

2024-07-15 22:23 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt
>              return manifests.map { arrayOf(it) }.toTypedArray()
I have added quite a few debug statements, seems like I don't see logging has implemented that need a separate ticket to add logging functionalities.

2024-07-16 14:59 UTC, cfarmer-fearless approved these changes

2024-07-16 15:53 UTC, merged