Allow sub templates in the simulator
CDCgov/data-exchange-upload pull request #416
Opened 2024-07-04 17:36 UTC by whytheplatypus

This allows the construction of very large structured files (like a huge hl7v2 file) without a massive impact on system resources.

2024-07-10 19:47 UTC, whytheplatypus commented on tests/bad-uploader/template.go
> +			// ok we know this generates the whole template, so it can be a memory issue
```suggestion
```

2024-07-11 13:35 UTC, cfarmer-fearless commented on tests/bad-uploader/tests/test copy.json
> +		"meta_destination_id": "dextesting",
Can we use a v2 manifest?

2024-07-11 13:56 UTC, cfarmer-fearless requested changes

2024-07-11 13:56 UTC, cfarmer-fearless commented on tests/bad-uploader/template.go
> +	if err == io.ErrUnexpectedEOF || peakErr == io.EOF {
Use `errors.Is`

2024-07-12 12:36 UTC, cfarmer-fearless approved these changes

2024-07-12 20:06 UTC, merged