Upload 1492/upload service bus for file ready
CDCgov/data-exchange-upload pull request #432
Opened 2024-07-26 14:50 UTC by cfarmer-fearless

Refactors Upload API event pub/sub to use Azure service bus instead of Azure Event Grid.

Still TODO
- Load testing
- Code cleanup
- Dead letter queue (separate PR)
- Refactor PS API health check from "service bus" service name to "Reporting"

2024-07-26 15:54 UTC, whytheplatypus requested changes

2024-07-26 15:54 UTC, whytheplatypus commented on upload-server/cmd/cli/processor.go
> +			logger.Error("failed to connect to event service bus", "error", err)
return this, if it can't connect the system probably shouldn't start up, same for other errors here.

2024-07-26 15:54 UTC, whytheplatypus commented on upload-server/internal/event/azure.go
> +	client, err := azservicebus.NewClientFromConnectionString(connString, &azservicebus.ClientOptions{
you can just return here if you want.

2024-07-26 17:57 UTC, cfarmer-fearless commented on upload-server/cmd/cli/processor.go
> +			logger.Error("failed to connect to event service bus", "error", err)
Done

2024-07-26 17:57 UTC, cfarmer-fearless commented on upload-server/internal/event/azure.go
> +	client, err := azservicebus.NewClientFromConnectionString(connString, &azservicebus.ClientOptions{
Done

2024-07-31 12:40 UTC, whytheplatypus requested changes

2024-07-31 12:40 UTC, whytheplatypus commented on upload-server/cmd/cli/processor.go
> +func NewEventSubscriber[T event.Identifiable](ctx context.Context, appConfig appconfig.AppConfig, memChan chan T) (event.Subscribable[T], error) {
needing the pass the memChan for just one case is causing complexity. Make that internal to the event package and the memory implementation. One way to do this currently, which can be extended later is to make a `GetChannel[T]() chan T` function in event.go that returns event.FileReadyChan for now.. and use it as the default for MemoryPublisher and MemorySubscriber.

2024-07-31 12:40 UTC, whytheplatypus commented on upload-server/cmd/cli/processor.go
> +					err = process(ctx, e)
```suggestion
					err := process(ctx, e)
```

2024-07-31 12:40 UTC, whytheplatypus commented on upload-server/internal/event/publish.go
> +type AzurePublisher[T Identifiable] struct {
move this closer to it's method implementations

2024-07-31 12:40 UTC, whytheplatypus commented on upload-server/internal/event/publish.go
> +	EventType   string
Remove EventType for simplification

2024-07-31 12:40 UTC, whytheplatypus commented on upload-server/internal/event/publish.go
> +		queueResp, err := ap.AdminClient.GetQueue(ctx, ap.Config.Queue, nil)
this says it will return a `nil, nil` response if the queue doesn't exist. Need a check for that.

2024-07-31 12:40 UTC, whytheplatypus commented on upload-server/internal/event/subscribe.go
> +	logger.Error("failed to handle event", "event", e, "error", err.Error())
if you wanted to test dead lettering or retries or something you could have this put the event back on the channel.

2024-07-31 12:40 UTC, whytheplatypus commented on upload-server/internal/event/subscribe.go
> +	// TODO dead letter message
can a basic version of this be included in this pr
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus@v1.6.1#Receiver.DeadLetterMessage

2024-07-31 13:23 UTC, cfarmer-fearless commented on upload-server/cmd/cli/processor.go
> +func NewEventSubscriber[T event.Identifiable](ctx context.Context, appConfig appconfig.AppConfig, memChan chan T) (event.Subscribable[T], error) {
Not sure if this is possible.  With type params in the return type, Go explicitly expects `chan T` as the return type.

2024-07-31 16:17 UTC, whytheplatypus approved these changes

2024-07-31 16:57 UTC, merged