UPLOAD-1648/redis-client-improvements
CDCgov/data-exchange-upload pull request #446
Opened 2024-08-13 17:15 UTC by cfarmer-fearless

This patch is to address some recent issues found with our redis file locker implementation.  Some highlights include
- Better default logic so the locker defaults to the memory locker instead of nil when the redis uri is provided but can't connect to Redis.
- Additional nil checks when using the client.  The original outage was caused by a panic from referencing the client, which became nil at some point.  It is still not clear what caused it to become nil.
- Building off the last point, we may want to create a new client for every upload instead of having a long lived client.

2024-08-14 21:17 UTC, whytheplatypus requested changes

2024-08-14 21:17 UTC, whytheplatypus commented on upload-server/pkg/redislocker/redislocker.go
>  	}
with the default options this isn't needed.

2024-08-14 21:17 UTC, whytheplatypus commented on upload-server/pkg/redislocker/redislocker.go
Could assert that CreateMutex and logger aren't nil here after all the options run just to be extra defensive

2024-08-14 22:49 UTC, cfarmer-fearless commented on upload-server/pkg/redislocker/redislocker.go
>  	}
removed

2024-08-14 22:49 UTC, cfarmer-fearless commented on upload-server/pkg/redislocker/redislocker.go
done

2024-08-15 21:04 UTC, whytheplatypus commented
can the `redislockerhealth` module now be removed?

2024-08-16 13:28 UTC, whytheplatypus approved these changes

2024-08-16 13:30 UTC, merged