Example metrics for uploads per data_stream
CDCgov/data-exchange-upload pull request #447
Opened 2024-08-14 14:17 UTC by whytheplatypus

2024-08-14 19:28 UTC, cfarmer-fearless commented on upload-server/cmd/cli/hooks.go
> +			// no op.. should be something else
Assuming this would throw some kind of "invalid metadata" error.

2024-08-14 19:30 UTC, cfarmer-fearless reviewed
Looks like a good start

2024-08-19 18:01 UTC, whytheplatypus commented
Testing example:
```
podman-compose up -d
# go to http://localhost:3000/d/eduxvq8up8f7kb/dex-dashboard?orgId=1&refresh=5s to see metrics, upload a file or two and watch them change
```

2024-08-22 15:50 UTC, cyber-decker requested changes
I was able to fire this up and launch the application just fine.  Looks like upload is working as expected.  I found the `demo-client-node-js` tool in `/upload-server/example/demo-client-node-js` to be really helpful here.

The metrics were getting reported correctly on the `localhost:8080/metrics` endpoint.  It looks like and things were mostly showing up on the dashboard but I did run in to a few things that might require some changes on the dashboard:

- Active Uploads was not correctly configured in grafana and was not showing any changes at all.  No metric was set for this dashboard tile. Might want to set this to `dex_server_active_uploads` with time series view.
- Uploads might be better as a time series graph.  The bar graph over time gives some weird, extrapolated metrics that don't really represent well what the graph is showing.   
- HTTP Responses is working fine, but, maybe something different than the pie chart.  The graph could get flooded with something like tons of patch requests for small chunks and you can't even see the rest of the graph unless you hide the patch responses.  This may be better as straight numbers or maybe bars?  Because the values can vary so differently, the percentage difference is too big when one thing is heavily inflated.

Other than that, the metrics seem to be getting into the system as expected, just need to tweak the display/output.

2024-08-22 15:50 UTC, cyber-decker commented on upload-server/grafana/provisioning/dashboards/dex.json
> +    {
This seems to be the start of the Active Uploads config.  Needs an appropriate target/expression to be used for displaying the results.

2024-08-22 15:50 UTC, cyber-decker commented on upload-server/grafana/provisioning/dashboards/dex.json
> +      "type": "barchart"
`timeseries` might work well here.  It was easier to visualize the change in upload counts over time with that.

2024-08-26 18:45 UTC, thetif approved these changes
looks good to me
checked out the new metrics dashboard and it's updating correctly

2024-08-27 18:06 UTC, cyber-decker requested changes
Needs one more little thing to finish here to get the docker compose configs right to point to the correct grafana/prometheus configs.   

I did that locally and it's looking good.  The dashboards looks great now and are reporting things nicely!

2024-08-27 18:06 UTC, cyber-decker commented on upload-server/docker-compose.yml
> +      - ./config/local/prometheus:/etc/prometheus
There's nothing in the `./config/local` folders.  I think the things in `./configs/local` need to be moved in to there or change the target in the docker-compose configuration on this line. 

This is causing prometheus/grafana to get some errors on startup and not load the dex dashboards.

2024-08-27 18:06 UTC, cyber-decker commented on upload-server/docker-compose.yml
> +      - ./config/local/grafana/provisioning:/etc/grafana/provisioning
Same problem as above.  needs to be either `./configs/local` or move the stuff from `./config/local` to this folder or change the target here in the docker-compose. 

Dashboards won't load up with this configuration.

2024-08-28 14:54 UTC, cyber-decker approved these changes
Looks great!

2024-08-28 19:23 UTC, merged