Playwright accessibility tests
CDCgov/data-exchange-upload pull request #456
Opened 2024-08-22 19:53 UTC by cyber-decker

TBD

2024-08-29 12:00 UTC, cfarmer-fearless requested changes

2024-08-29 12:00 UTC, cfarmer-fearless commented on tests/smoke/playwright/test/upload-test-accessibility.spec.ts
> +        expect(results.violations).toEqual([]);
Use `toHaveLength` https://playwright.dev/docs/api/class-genericassertions#generic-assertions-to-have-length

2024-08-29 12:00 UTC, cfarmer-fearless commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +    { dataStream: "celr", route: "csv" },
Could move this list to a separate ts file and export it, or export getters like `getAll` or `getByDataStream` to do some simple filtering

2024-08-30 18:36 UTC, cyber-decker commented on tests/smoke/playwright/test/upload-test-accessibility.spec.ts
> +        expect(results.violations).toEqual([]);
The disadvantage here would be that if the length is different, playwright will just tell us the violation length is different and not dump the list of violations.  This is a bit of a shortcut (maybe a hack?) that if the violations array isn't empty, it will show us the diff and output the violations list as well.

2024-08-30 18:39 UTC, cyber-decker commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +    { dataStream: "celr", route: "csv" },
I thought about this too, but part of it abstracts away what the test is doing and makes it hard to know what's being tested.  I think there is room here to extend this object as well adding in specific expectations to check for, which might make your argument here more compelling because a really complex object as an input will make the test hard to read.  

Do you think we need to change this now or can we noodle over this a little and change it in a future story?

2024-09-03 18:00 UTC, cfarmer-fearless approved these changes

2024-09-04 13:39 UTC, merged