s3 file copy
CDCgov/data-exchange-upload pull request #462
Opened 2024-08-28 04:21 UTC by rohitpanwar

2024-08-29 12:03 UTC, cfarmer-fearless commented on upload-server/internal/appconfig/appconfig.go
> +type S3FolderConfig struct {
Probably don't need this

2024-08-29 12:04 UTC, cfarmer-fearless commented on upload-server/internal/postprocessing/deliver.go
> +	return rsp
Also need to ping the dest bucket

2024-08-29 12:11 UTC, cfarmer-fearless commented on upload-server/internal/postprocessing/deliver.go
> +	createResp, err := sd.SrcClient.CreateMultipartUpload(ctx, &s3.CreateMultipartUploadInput{
We could check the file size and use the simple `CopyObject` operation if it's less than 5gb

2024-08-29 12:22 UTC, cfarmer-fearless commented on upload-server/internal/postprocessing/deliver.go
> +	uploadPartCopyResp, err := sd.SrcClient.UploadPartCopy(ctx, &s3.UploadPartCopyInput{
Seeing this example https://docs.aws.amazon.com/AmazonS3/latest/userguide/CopyingObjectsMPUapi.html
Looks like you need to copy parts in a loop.  Unless it's possible to copy all at once?

2024-09-05 14:18 UTC, whytheplatypus commented on upload-server/internal/postprocessing/deliver.go
can the s3 changes be moved to a new file? it'll make merging some pieces together easier

2024-09-06 12:46 UTC, whytheplatypus requested changes
could a new partial compose file be included with minio or similar for local testing?

2024-09-06 12:46 UTC, whytheplatypus commented on upload-server/internal/postprocessing/s3.go
> +	destFileName, err := getDeliveredFilename(ctx, sd.Target, tuid, manifest)
because this is such a specific case of having to transform the ID, include a comment so it's clear when it may need to change

2024-09-09 14:20 UTC, cfarmer-fearless commented on upload-server/internal/postprocessing/s3.go
> +	destFileName, err := getDeliveredFilename(ctx, sd.Target, tuid, manifest)
Done

2024-09-09 14:22 UTC, whytheplatypus approved these changes

2024-09-09 18:04 UTC, merged