A structureal refactor to prepair for the delivery behavior
CDCgov/data-exchange-upload pull request #466
Opened 2024-08-28 19:05 UTC by whytheplatypus

Goal of this work is to provide two interfaces:
- Source
- Destination

and logic to combine them.

2024-08-28 19:26 UTC, cfarmer-fearless commented on upload-server/cmd/cli/routing.yml
> +    manifest_conditions:
Would it be better to put the data stream and route at the top level, and have a field for manifest conditions and a list of delivery objects?

2024-08-29 13:36 UTC, cfarmer-fearless commented on upload-server/cmd/cli/route.go
> +	fromPathStr := appconfig.LoadedConfig.LocalFolderUploadsTus + "/" + appconfig.LoadedConfig.TusUploadPrefix
Assuming this'll use some interface at some point instead of a file specific implementation?

2024-08-30 13:26 UTC, whytheplatypus commented on upload-server/cmd/cli/route.go
> +	src, ok := delivery.GetSource("upload")
move the source name to a body attribute and default to something configurable.

2024-08-30 13:26 UTC, whytheplatypus commented on upload-server/cmd/cli/serve.go
> +	err = delivery.RegisterAllTargets(ctx, appConfig)
rename, only pass what's necessary from appConfig

2024-08-30 13:26 UTC, whytheplatypus commented on upload-server/internal/delivery/azure.go
> +	checkpointContainerClient, err := storeaz.NewContainerClient(config.AzureStorageConfig, config.ContainerName)
rename

2024-08-30 13:26 UTC, whytheplatypus commented on upload-server/internal/delivery/azure.go
> +}
remove

2024-08-30 13:26 UTC, whytheplatypus commented on upload-server/internal/delivery/deliver.go
> +}
remove

2024-08-30 13:26 UTC, whytheplatypus commented on upload-server/internal/postprocessing/postprocessor.go
> +	return delivery.Deliver(ctx, e.UploadId, src, d)
I think bring the reports up to here.

2024-08-30 13:50 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +		//health.Register(edavDeliverer)
Don't we still want to have health checks for all of the destinations?

2024-08-30 13:59 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +type Destination interface {
Would be good to embed the `health.Checkable` interface here

2024-09-05 19:41 UTC, cfarmer-fearless requested changes
Overall looks solid.  Small comment to expand the destination url value to include the FQDN if it's an azure destination

2024-09-05 19:41 UTC, cfarmer-fearless commented on upload-server/internal/delivery/file.go
> +	log.Println("calling file health")
Remove debug log

2024-09-05 19:41 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +type Destination interface {
Covered by type check

2024-09-05 19:41 UTC, cfarmer-fearless commented on upload-server/internal/postprocessing/postprocessor.go
> +	uri, err := delivery.Deliver(ctx, e.UploadId, src, d)
For azure, looks like it's just returning the blob name without the storage account container url.

2024-09-09 20:09 UTC, cfarmer-fearless approved these changes

2024-09-09 20:09 UTC, merged