Agnostic auth v1
CDCgov/data-exchange-upload pull request #468
Opened 2024-09-03 15:28 UTC by ZacharyRizer

2024-09-03 21:15 UTC, cfarmer-fearless commented on upload-server/internal/appconfig/appconfig.go
> +	OauthIntrospectionUrl string `env:"OAUTH_INTROSPECTION_URL, default=https://apigw-stg.cdc.gov:8443"`
Could group these into an Oauth config type struct and provide a prefix of `OAUTH_`

2024-09-03 21:19 UTC, cfarmer-fearless commented on upload-server/internal/middleware/authverification.go
> +func validateJWT(ctx context.Context, w http.ResponseWriter, token string) bool {
These validation functions could be a bit more testable if they returned errors and didn't take a response writer.  The http handler can take care of the http response stuff based on the error

2024-09-03 21:21 UTC, cfarmer-fearless commented on upload-server/internal/middleware/authverification.go
> +	var introspectionResponse struct {
Define this struct at the package level

2024-09-03 21:22 UTC, cfarmer-fearless commented on upload-server/internal/middleware/authverification.go
> +	if err := json.NewDecoder(resp.Body).Decode(&introspectionResponse); err != nil {
Use `json.Unmarshal` instead of `json.NewDecoder`

2024-09-03 21:24 UTC, cfarmer-fearless commented on upload-server/internal/middleware/authverification.go
> +	scopeMap := make(map[string]bool)
Is the map necessary?  Can't you loop over actual and do `slice.Contains` on required?

2024-09-04 13:07 UTC, ZacharyRizer commented on upload-server/internal/middleware/authverification.go
> +	scopeMap := make(map[string]bool)
Probably not, been a bit since I used Go, I'll looking into optimizing.

2024-09-04 13:27 UTC, ZacharyRizer commented on upload-server/internal/appconfig/appconfig.go
> +	OauthIntrospectionUrl string `env:"OAUTH_INTROSPECTION_URL, default=https://apigw-stg.cdc.gov:8443"`
Good call, done.

2024-09-04 13:36 UTC, ZacharyRizer commented on upload-server/internal/middleware/authverification.go
> +func validateJWT(ctx context.Context, w http.ResponseWriter, token string) bool {
Good call, refactored.

2024-09-04 13:39 UTC, ZacharyRizer commented on upload-server/internal/middleware/authverification.go
> +	var introspectionResponse struct {
Done

2024-09-04 13:44 UTC, ZacharyRizer commented on upload-server/internal/middleware/authverification.go
> +	if err := json.NewDecoder(resp.Body).Decode(&introspectionResponse); err != nil {
I would need to put the resp.Body into a byte array, using the io package I believe to use Unmarshal. Which is more preferable in your opinion?

2024-09-04 13:48 UTC, ZacharyRizer commented on upload-server/internal/middleware/authverification.go
> +	scopeMap := make(map[string]bool)
Simplified.

2024-09-05 14:54 UTC, whytheplatypus commented on upload-server/internal/middleware/authverification.go
> +		}
consider changing this check to be based off what's configured: if an IssuerURL is provided validateJWT and return, if an Info endpoint is provided validateOpaqueToken and return.

2024-09-05 14:56 UTC, whytheplatypus commented on upload-server/internal/middleware/authverification.go
> +		return fmt.Errorf("inactive token")
create some constants for errors so that the middleware can react to them. (e.g. InactiveTokenErr -> 401)

2024-09-05 15:03 UTC, ZacharyRizer commented on upload-server/internal/middleware/authverification.go
> +		}
Where are you thinking the configuration will live? Currently the issuer is an env variable, and I was assuming we'd always have an issuer present. Same thing for the `endpoint`, are you thinking that we'd either have an issuer or introspection url? I was thinking we'd want it to be open to have both jwt's and opaque tokens be ingested at the same time.

2024-09-05 16:44 UTC, ZacharyRizer commented on upload-server/internal/middleware/authverification.go
> +		return fmt.Errorf("inactive token")
Updated

2024-09-23 16:51 UTC, cfarmer-fearless approved these changes
Small readme tweak but looks great!  Also wondering if the middleware function names can be improved to be a verb instead of a noun, like `VerifyOauth` or `WithOauthVerification`

2024-09-23 16:51 UTC, cfarmer-fearless commented on upload-server/readme.md
> +##### Configuration
Use level 4 header instead of level 5

2024-09-25 19:44 UTC, whytheplatypus requested changes
Wrap the tus and info handler in this.

2024-09-25 19:44 UTC, whytheplatypus commented on upload-server/internal/middleware/authverification.go
> +		authEnabled := appconfig.LoadedConfig.OauthConfig.AuthEnabled
pull this dependency on appconfig out. So these handlers and functions can be methods on a struct that has things like `IssuerURL`

2024-09-27 15:57 UTC, ZacharyRizer commented on upload-server/internal/middleware/authverification.go
> +		authEnabled := appconfig.LoadedConfig.OauthConfig.AuthEnabled
Refactored

2024-09-30 11:55 UTC, whytheplatypus approved these changes

2024-09-30 11:58 UTC, merged