1671 - UI Update
CDCgov/data-exchange-upload pull request #469
Opened 2024-09-03 16:34 UTC by Sun-Mountain

Added:
- Banner with DEX logo
- Favicon in tab
- Assured accessibility
- Can be redirected to first form if user clicks on logo

2024-09-03 21:12 UTC, cfarmer-fearless requested changes

2024-09-03 21:12 UTC, cfarmer-fearless commented on upload-server/internal/ui/index.html
> +        <div id="nav-banner"></div>
Should we use a `nav` tag outside of the `main` tag?

2024-09-03 21:13 UTC, cfarmer-fearless commented on upload-server/internal/ui/index.html
> +            <h1>Welcome to DEX Upload</h1>
Could also add a sub heading saying something like "input a data stream and route to start an upload"

2024-09-04 02:09 UTC, cfarmer-fearless requested changes

2024-09-04 02:09 UTC, cfarmer-fearless commented on upload-server/internal/ui/assets/banner.js
> +(function webBanner() {
Might be a good opportunity to use nested templates and have the nav bar embedded during the server side generation. It would save a JS file load and allow the navbar to be expanded more easily if need be. You'll need to rework the home page handler to execute the temate for index.html but should be a small change. Here's an article I found that has an example of how this can be implemented. https://medium.com/@sheshbabu/implementing-react-like-composition-using-gos-html-template-ee007835ceaa

2024-09-04 17:35 UTC, Sun-Mountain commented on upload-server/internal/ui/assets/banner.js
> +(function webBanner() {
Was not aware this was an option!

2024-09-09 20:06 UTC, thetif approved these changes
LGTM, just remove the scripts for /assets/banner.js

2024-09-09 20:06 UTC, thetif commented on upload-server/internal/ui/index.html
> +<script src="/assets/banner.js"></script>
no longer needed

2024-09-09 20:06 UTC, thetif commented on upload-server/internal/ui/manifest.tmpl
> +    <script src="/assets/banner.js"></script>
no longer needed

2024-09-09 20:06 UTC, thetif commented on upload-server/internal/ui/upload.tmpl
> +    <script src="/assets/banner.js"></script>
no longer needed

2024-09-09 20:06 UTC, thetif approved these changes
LGTM, just remove the scripts for /assets/banner.js

2024-09-09 20:08 UTC, thetif approved these changes

2024-09-09 20:09 UTC, merged