Automate graphql get reports functionalities
CDCgov/data-exchange-upload pull request #474
Opened 2024-09-05 16:49 UTC by GSA2024

2024-09-09 15:03 UTC, gulnaz-cdc commented on tests/smoke/kotlin/src/test/kotlin/ProcStat.kt
> +        .apply {
Check if using relaxedHTTPSValidation() is necessary, as it might lower security by skipping SSL checks. Make sure it's safe for the environment you're testing

2024-09-10 14:13 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/ProcStat.kt
> +        .apply {
Agree that it's less than ideal, but since we know this is hitting an environment only accessible from cdc network, it's ok to use.

2024-09-10 14:24 UTC, cfarmer-fearless requested changes

2024-09-10 14:24 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/ProcStat.kt
> +                        log.info("Metadata Verify - Upload ID: $uploadId, Dex Ingest DateTime: $dexIngestDateTime")
Assert that the upload id equals the uid var defined above.  
Assert that the metadata verify report status is successful and there are no isses.

2024-09-10 14:24 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/ProcStat.kt
> +                            log.info("Transform Action: $action, Field: $field, Value: $value")
Assert that there is at least one transform within the content of this report

2024-09-10 14:24 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/ProcStat.kt
> +                        log.info("Schema Name: $schemaName, Status: $status")
Many of these logs can be debug

2024-09-10 14:24 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/ProcStat.kt
> +                        log.info("Upload Status - Filename: $filename, TGUID: $tguid, Offset: $offset, Size: $size")
Assert that the size and offset match

2024-09-10 14:24 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/ProcStat.kt
> +            log.error("Test failed due to exception: ${e.message}", e)
This catch is probably unnecessary.  Just let the test fail instead of catching the exception

2024-09-10 21:02 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/ProcStat.kt
> +                        log.info("Schema Name: $schemaName, Status: $status")
Added debug logs

2024-09-11 15:02 UTC, cfarmer-fearless approved these changes

2024-09-11 15:03 UTC, merged

2024-09-11 17:32 UTC, cyber-decker commented on tests/smoke/kotlin/src/test/kotlin/ProcStat.kt
> +        .apply {
This is a common practice in test envionments since we are using self signed certs in the test envs.  This is normal and usual unless we are specifically confirming that we need valid certs in the test environments.  I feel like that's a different kind of test.