UPLOAD-1695 Show upload status of file in info
CDCgov/data-exchange-upload pull request #475
Opened 2024-09-05 19:38 UTC by thetif

- Reads the last line of the upload-status report
- Gets the offset and size from that line
- Uses that to determine the status
	- Not Started
	- In Progress
	- Complete
	- Failed
- Includes this status in the /info endpoint for the file

Additional changes: Changed a little about the s3store so that it is a little more consistent with the azstore.

2024-09-13 12:54 UTC, cfarmer-fearless requested changes

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/internal/ui/assets/file-info.css
> +  color: rgb(0, 94, 201) !important;
Can we remove the `!important`?

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/internal/ui/assets/tusclient.js
> +  if (!fileList) {
Could do `if (!fileList || fileList.length() < 1)` to consolidate this if statement with the next one.

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/internal/ui/assets/tusclient.js
> +    case "0": // 0 is Initiated
Could use const vars for these values

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/internal/ui/components/navbar.go
> +	Newuploadbtn Newuploadbtn
Use capital case `NewUploadBtn`

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/internal/ui/index.html
> +    <div>
Rebase from main to take care of this navbar duplication

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/internal/ui/ui.go
> +	"AllLowerCase":   AllLowerCase,
Should be able to just put `strings.ToUpper` and `strings.ToLower` as the values in this map and remove the wrapper functions `AllLowerCase` and `AllUpperCase`

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/internal/ui/ui.go
> +			uploadStatusLevel = 0
Incrementing const ints is a good opportunity for using [iota](https://go.dev/wiki/Iota)

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/internal/ui/upload.tmpl
> +  <script>
Combine these two script tags

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/pkg/fileinspector/status.go
> +	defer f.Close()
Should only need one `defer f.Close()`

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/pkg/fileinspector/status.go
> +	uploadCompletedFileInfo, errComplete := os.Stat(uploadCompletedReportFilename)
Convention for the error object to just be `err`

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/pkg/fileinspector/status.go
> +	if errComplete == nil {
Usually good to check if err not nil so you don't swollow an error.  Can be something like
```
if err != nil
  if err is os.ErrNotExist
    return empty file info status, nil
  return nil, err // this is the catch all
return populated file info statis, nil
```

2024-09-13 12:54 UTC, cfarmer-fearless commented on upload-server/pkg/info/info.go
> +	UploadStatus FileUploadStatus `json:"upload_status"`
Make sure to expand the unit tests to cover this new information

2024-09-16 15:23 UTC, thetif commented on upload-server/pkg/fileinspector/status.go
> +	defer f.Close()
oops, merge issue

2024-09-16 15:26 UTC, thetif commented on upload-server/pkg/fileinspector/status.go
> +	if errComplete == nil {
In this case, I'm expecting error to be not null because the upload-complete file probably won't be there. I'm trying to shortcut the rest of the code if the error is null because that means the file is there and the upload is complete. I don't want to return anything if the error is not empty, I want it to continue checking the other files. I can nest is all under that ErrNotExist but that seemed a little messy.

2024-09-17 12:06 UTC, cfarmer-fearless requested changes
Minor changes, but looks excellent overall

2024-09-17 12:06 UTC, cfarmer-fearless commented on upload-server/internal/ui/ui.go
> +	"KebabCase": 			KebabCase,
Run a `go fmt ./...` to take care of formatting all of the files and makes the linting PR check happy

2024-09-17 12:06 UTC, cfarmer-fearless commented on upload-server/cmd/cli/info.go
> +		containerClient, err := stores3.New(ctx, appConfig.S3Connection)
Revert this rename.  S3 doesn't have the concept of a container.

2024-09-17 12:10 UTC, cfarmer-fearless commented
Seeing this error on initial load of the upload status page
![image](https://github.com/user-attachments/assets/8abb7e5a-fe80-4c78-991c-5b0ccbe7b757)

2024-09-17 12:13 UTC, cfarmer-fearless commented
All of the values here are being capitalized.  They probably don't need to be manipulated.
![image](https://github.com/user-attachments/assets/87f35e73-0355-426a-ba60-a8a324c04170)

2024-09-17 12:16 UTC, cfarmer-fearless commented
Got this error when resuming an upload.  This usually means the client tried to create a new upload with an empty manifest instead of resume one
![image](https://github.com/user-attachments/assets/d981446c-b9c3-447a-85d6-c2a50cf261d2)

2024-09-17 12:18 UTC, cfarmer-fearless commented
Can probs have some better formatting for the file size
![image](https://github.com/user-attachments/assets/3b8afda3-8766-40bd-ac60-968357f6c1c1)

2024-09-17 12:23 UTC, cfarmer-fearless commented
Looks like this is showing the current file size based on how many bytes have been uploaded.  Can be a future improvement to show total file size here and maybe current number of bytes sent in another place
![image](https://github.com/user-attachments/assets/6888b846-29cb-49ca-a884-f03972c41943)

2024-09-17 13:07 UTC, thetif commented on upload-server/internal/ui/ui.go
> +	"KebabCase": 			KebabCase,
thanks!

2024-09-17 19:46 UTC, cfarmer-fearless approved these changes

2024-09-17 21:31 UTC, merged