Refactor of top level tests
CDCgov/data-exchange-upload pull request #484
Opened 2024-09-12 14:53 UTC by whytheplatypus

2024-09-13 17:15 UTC, whytheplatypus commented on upload-server/cmd/main_test.go
> +	os.Setenv("EDAV_STORAGE_KEY", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")
this is the example key from azurite, [public here](https://github.com/Azure/Azurite?tab=readme-ov-file#default-storage-account)

2024-09-26 14:10 UTC, thetif approved these changes
looks good

2024-09-26 16:01 UTC, cfarmer-fearless requested changes
Minor cleanup but looks great overall

2024-09-26 17:32 UTC, cfarmer-fearless commented
Getting this when running locally
`{"time":"2024-09-26T17:32:09.308398739Z","level":"ERROR","source":{"function":"github.com/cdcgov/data-exchange-upload/upload-server/cmd.main","file":"/code/cmd/main.go","line":92},"msg":"error starting app, error initialize dex handler","app_info":{"System":"
DEX","Product":"UPLOAD API","App":"UPLOAD SERVER","Env":"DEV"},"error":"failed to connect to edav deliverer target not enough information given to connect to container edav"}`

2024-09-26 17:38 UTC, cfarmer-fearless commented on upload-server/docker-compose.testing.yml
> +      - AZURITE_STORAGE_KEY=${AZURE_STORAGE_KEY}
Where is this getting populated?

2024-09-26 18:59 UTC, cfarmer-fearless commented on upload-server/docker-compose.testing.yml
> +      - AZURITE_STORAGE_KEY=${AZURE_STORAGE_KEY}
Coming from command line

2024-09-27 20:56 UTC, cfarmer-fearless approved these changes

2024-09-30 12:10 UTC, merged