UPLOAD-1725 CSRF
CDCgov/data-exchange-upload pull request #505
Opened 2024-09-23 22:12 UTC by thetif

Added gorilla/csrf to prevent csrf

2024-09-24 17:21 UTC, cfarmer-fearless reviewed
Looks pretty solid so far!

2024-09-24 17:21 UTC, cfarmer-fearless commented on upload-server/internal/appconfig/appconfig.go
> +	CsrfToken            string `env:"CSRF_TOKEN, default=SwVgY4SfiXNyXCT4U6AvLNURDYS7J+Y/V2j4ng2UVp0XwQY0IUELUT5J5b/FATcE"`
Ok to commit this default?

2024-09-24 19:37 UTC, thetif commented on upload-server/internal/appconfig/appconfig.go
> +	CsrfToken            string `env:"CSRF_TOKEN, default=SwVgY4SfiXNyXCT4U6AvLNURDYS7J+Y/V2j4ng2UVp0XwQY0IUELUT5J5b/FATcE"`
It's just a random string of 32 bytes. It's ok to commit it because it's only used for this local server, but I can also remove it, we would need to update the instructions to say that setting the CSRF_TOKEN is required.

2024-09-26 13:37 UTC, cfarmer-fearless requested changes

2024-09-26 13:37 UTC, cfarmer-fearless commented on upload-server/internal/appconfig/appconfig.go
> +	CsrfToken            string `env:"CSRF_TOKEN, default=SwVgY4SfiXNyXCT4U6AvLNURDYS7J+Y/V2j4ng2UVp0XwQY0IUELUT5J5b/FATcE"`
Fine to leave then.  Add a comment saying it's for local use only and not sensitive.

2024-09-26 13:37 UTC, cfarmer-fearless commented on upload-server/testing/cli_test.go
> +const TestFolderUploadsTus = "uploads"
The tests use a `test` subdir instead of `uploads`

2024-09-26 13:44 UTC, thetif commented on upload-server/testing/cli_test.go
> +const TestFolderUploadsTus = "uploads"
yes, I duplicated the same structure in the tests, so it's pointing to the uploads dir inside the testing dir

2024-09-26 15:05 UTC, whytheplatypus requested changes

2024-09-26 15:05 UTC, whytheplatypus commented on upload-server/internal/delivery/file.go
> +	info, err := os.Stat(fd.Path)
consider using `fs.Stat(fd.FS, ".")` instead, fewer parts to coordinate

2024-09-26 15:05 UTC, whytheplatypus commented on upload-server/internal/delivery/file.go
> +	Path string
Adds complexity for the health reporting.. if a name is needed maybe changing registering a health check to include a name is needed.

2024-09-26 15:05 UTC, whytheplatypus commented on upload-server/internal/ui/ui.go
> +	}).Methods("POST")
Should stay a GET so that it can be used as a bookmark to go directly to a form for the given datastream/route

2024-09-26 15:42 UTC, thetif commented on upload-server/cmd/cli/serve.go
> +	http.Handle("/info/", uploadInfoHandler)
it was doing something weird before where it wasn't handling hitting the /info endpoint correctly and it was returning a 200 if there was no uploadId. That's not happening now so it was probably fixed in other parts of the code. Removing it.

2024-09-26 16:13 UTC, thetif commented on upload-server/internal/ui/ui.go
> +	}).Methods("POST")
We can't use the CSRF protection for the form without putting it in the post. Now that we have CSRF we cannot let them bookmark directly to the manifest form. That is essentially a request forgery because you aren't coming at that page from the intended location. We could switch it back to a GET but then we lose the CSRF restrictions on the index page. There is no way to do both though. I thought @AJKimpo had said we could just change the messaging and tell them they have to go to the index page first. I am willing to remove the CSRF from the index page, switch /manifest back to a GET, and whitelist it, if that's how we want to go.

2024-09-26 18:16 UTC, thetif commented on upload-server/cmd/cli/serve.go
> +	http.Handle("/info/", uploadInfoHandler)
looked at this again and I was able to figure it out, the [docs](https://cs.opensource.google/go/go/+/go1.23.1:src/net/http/server.go;l=2505) say that the url path handling changed from Go 1.21 and 1.22 and now "/" is an implicit wildcard, so it will match anything not matched in the other paths. So if you hit `/info` or `/route` with no `UploadId` it would treat it like you hit the `/` endpoint and respond with a `200` and json like this
```json
{"system":"DEX","dex_product":"UPLOAD API","dex_app":"upload server","server_time":"2024-09-26T14:13:04-04:00"}
```
which the upload template was not to happy with. Now if you want `"/"` to only work for `/` you have to set it as `"/{$}"`. I changed it to this and now if you hit `/info` or `/route` it returns a 404 as you would expect

2024-09-27 13:40 UTC, whytheplatypus commented on upload-server/cmd/cli/serve.go
> +	http.Handle("/info/", uploadInfoHandler)
woah, awesome find, i didn't know they'd changed that under the hood!

2024-09-27 13:48 UTC, whytheplatypus approved these changes

2024-09-27 14:10 UTC, cfarmer-fearless commented on upload-server/testing/cli_test.go
> -					// Remove and re-route the file
Is this test for re-routing the file being preserved somewhere I'm not seeing?

2024-09-27 14:29 UTC, thetif commented on upload-server/pkg/azureinspector/azure.go
> +	uploadBlobClient := aui.TusContainerClient.NewBlobClient(aui.TusPrefix + "/" + id)
I'm attempting to resolve this issue which might not really be an issue

![CleanShot 2024-09-27 at 10 27 08](https://github.com/user-attachments/assets/63ce4fea-75ac-4d0a-a9f7-fc3bfab3b373)

I saw that filepath.Join uses the os specific file path separator and because azure and aws use urls, I was wondering if using filepath.Join was causing an issue with interpreting the url correctly. But I haven't been able to confirm that yet, or track down what's actually happening

2024-09-27 14:30 UTC, thetif commented on upload-server/testing/cli_test.go
> -					// Remove and re-route the file
yes, I moved it own into it's own test `TestRouteEndpoint` because it's seemed kind of heavy for doing on every test case, but if we need to test every case, I can move it back in

2024-09-27 14:57 UTC, cfarmer-fearless commented on upload-server/internal/ui/ui.go
> +	}).Methods("POST")
Should this be GET?

2024-09-27 14:59 UTC, cfarmer-fearless commented on upload-server/testing/cli_test.go
> +			// TODO probably best if this was in its own test function but this is at least good for happy path test for now
Can remove this TODO comment now

2024-09-27 15:00 UTC, cfarmer-fearless commented on upload-server/testing/cli_test.go
> -					// Remove and re-route the file
Perfect!

2024-09-27 15:06 UTC, cfarmer-fearless approved these changes

2024-09-27 15:42 UTC, merged