Upload 1744 playwright data stream route updates
CDCgov/data-exchange-upload pull request #514
Opened 2024-09-27 18:12 UTC by cyber-decker

2024-09-30 14:58 UTC, AJKimpo requested changes

2024-09-30 14:58 UTC, AJKimpo commented on tests/smoke/playwright/test/manifests.json
> +        "dataStream": "covid-bridge-vaccination",
Please remove the covid-bridge-vaccination section. This data stream has been decommissioned. I'm removing configs and updating kotlin tests now.

2024-09-30 14:59 UTC, AJKimpo commented on tests/smoke/playwright/test/manifests.json
> +        "dataStream": "covid-bridge-vaccination",
remove lines 6-8. the screen grab isolated the wrong lines.

2024-09-30 15:00 UTC, cfarmer-fearless commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        // Need to fix the server to enable these tests, they are currently valid when they shouldn't be
Add link to jira ticket

2024-09-30 15:03 UTC, cfarmer-fearless commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +            await expect(page.locator('body')).toContainText(`open v2/${dataStream}-${route}.json: `)
We may just rerender the same form with an error message.  I'm thinking that's a better UX than showing a raw error message from the server, and having the user guess to click their browser back button to go back to the form and try again.

2024-10-01 14:03 UTC, AJKimpo approved these changes
lgtm

2024-10-01 14:29 UTC, merged