Test branch
CDCgov/data-exchange-upload pull request #515
Opened 2024-09-30 13:49 UTC by GSA2024

This test validates the file information, confirms the file's manifest and upload status, and verifies successful deliveries to the target location.

2024-09-30 14:28 UTC, cyber-decker commented on tests/smoke/kotlin/src/test/kotlin/util/EnvConfig.kt
>          val DEX_STORAGE_CONNECTION_STRING: String = properties?.getProperty("dex.storage.connection.string") ?: System.getenv("DEX_STORAGE_CONNECTION_STRING")
I think we need to put this in the documentation to include what properties need to go into the local.properties file and maybe even where they can be found and perhaps a little bit about what they do in this test suite. I can't run this until I track down the INFO_URL that has been added in

2024-09-30 14:53 UTC, cfarmer-fearless requested changes

2024-09-30 14:53 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/Info.kt
> -    fun shouldReturnNotFoundGivenInvalidId() {
Why was this test removed?

2024-09-30 14:53 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
>      fun getToken(username: String, password: String): String {
Can you explain the changes to the `getToken` function?

2024-09-30 14:53 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
> +            .url("${EnvConfig.INFO_URL}/info/$id")
Shouldn't need a separate config variable for the info url.  Should be able to use the upload url appended with "/info".  Why do we need this new config variable?

2024-09-30 14:53 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
> +        Thread.sleep(1000) // wait to load delivery response
What's the reason for this wait?

2024-09-30 14:53 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
> +            logger.info("Raw response body: $responseBody")
Can be debug level log

2024-09-30 14:53 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
> +            logger.info("Raw response body: $responseBody")
Also can be a more specific message.  Raw response body from which request?  Which service?

2024-09-30 14:53 UTC, cfarmer-fearless commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
> +        httpClient.newCall(req).execute().use { response ->
Any benefit of handling the response with `use` instead of just storing it in a local var?

2024-09-30 15:04 UTC, cyber-decker commented on tests/smoke/kotlin/src/test/kotlin/Health.kt
> +            "ocio-ede-stg-upload-file-ready-subscription Event Subscriber",
These two are probably not going to be valid for other environments and are causing failures when I run this in test.  

This causes the assertion on line 44 to fail but it doesn't say why.

2024-09-30 15:58 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/EnvConfig.kt
>          val DEX_STORAGE_CONNECTION_STRING: String = properties?.getProperty("dex.storage.connection.string") ?: System.getenv("DEX_STORAGE_CONNECTION_STRING")
I agree. 
I check with Chase, there is no need of changing the endpoint url for info and health check, need to update back> If possible, I can check-in local properties too if everyone is ok

2024-09-30 16:24 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
> +            .url("${EnvConfig.INFO_URL}/info/$id")
Removed EnvConfig for info endpoint url, reverted upload url appended for info as-is

2024-09-30 16:53 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
>      fun getToken(username: String, password: String): String {
Logger used for debugging purposes. reverted the 'getToken' changes as it is not needed

2024-09-30 16:58 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
> +        httpClient.newCall(req).execute().use { response ->
`use` is safer, reduces the risk of resource leakage, and results in more concise and readable code. 

Since we have reverted changes as it not needed for both the methods `getToken` and `getFileInfo`

2024-09-30 17:01 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/Health.kt
> +            "ocio-ede-stg-upload-file-ready-subscription Event Subscriber",
Can I raise different PR/ticket for health check changes?

2024-09-30 17:01 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
> +        Thread.sleep(1000) // wait to load delivery response
Removed

2024-09-30 17:03 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
> +            logger.info("Raw response body: $responseBody")
Removed Raw response

2024-09-30 17:05 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/Info.kt
> -    fun shouldReturnNotFoundGivenInvalidId() {
Adding it back

2024-09-30 17:15 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/dex/DexUploadClient.kt
>      fun getToken(username: String, password: String): String {
Logger is added for debugging purposes.

2024-09-30 18:07 UTC, cyber-decker commented on tests/smoke/kotlin/src/test/kotlin/util/EnvConfig.kt
>          val DEX_STORAGE_CONNECTION_STRING: String = properties?.getProperty("dex.storage.connection.string") ?: System.getenv("DEX_STORAGE_CONNECTION_STRING")
I still think we should include this in documentation.  This was a very challenging point of getting these tests running.  Documenting what all of these properties are used for and where they should be set is necessary.

2024-09-30 21:40 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/Health.kt
> +            "ocio-ede-stg-upload-file-ready-subscription Event Subscriber",
Just added additional assertions to compare the list of actual services with a list of expected services, which checks for matching elements without considering order. If the lists don't match, a detailed error message is generated.

2024-09-30 22:05 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/Health.kt
> +            "ocio-ede-stg-upload-file-ready-subscription Event Subscriber",
Shall we add these two environment specific dependent services in EnvConfig file?
 "Event Publishing ocio-ede-tst-upload-file-ready-topic",
 "ocio-ede-tst-upload-file-ready-subscription Event Subscriber"
 @cfarmer-fearless @cyber-decker

2024-10-01 14:37 UTC, cyber-decker commented on tests/smoke/kotlin/src/test/kotlin/Health.kt
> +            "ocio-ede-stg-upload-file-ready-subscription Event Subscriber",
This seems complex. What would have to happen with other environments?  How would someone know what this should be changed to for any other environment this exists in?

2024-10-01 14:57 UTC, cyber-decker commented
When running the latest suite of tests, I currently have 62 tests passed and 7 failed tests.  None of them seem to be info related, but there is a health check related test that has not passed and some others that might need to grab the latest changes from main to address some datastream/route changes that have been made.

2024-10-01 16:01 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/util/EnvConfig.kt
>          val DEX_STORAGE_CONNECTION_STRING: String = properties?.getProperty("dex.storage.connection.string") ?: System.getenv("DEX_STORAGE_CONNECTION_STRING")
Shall I put local properties in readMedoc?
@cfarmer-fearless @cyber-decker

2024-10-01 18:31 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/Health.kt
> +            "ocio-ede-stg-upload-file-ready-subscription Event Subscriber",
Fix tests for Health check - Added health check dependent services and verifies the status for the list of services for a specific environment.

The environment (dev, tst, stg, prd) is extracted from the UPLOAD_URL. If the environment in the URL is not recognized, an exception is thrown.

2024-10-02 13:51 UTC, cyber-decker approved these changes
I think this looks good for now.  We should definitely keep iterating over updating the documentation for these tests.

2024-10-02 15:21 UTC, GSA2024 commented on tests/smoke/kotlin/src/test/kotlin/Info.kt
> -    fun shouldReturnNotFoundGivenInvalidId() {
It was removed accidentally it seems, `shouldReturnNotFoundGivenInvalidId` added back

2024-10-03 13:19 UTC, cfarmer-fearless approved these changes

2024-10-03 13:24 UTC, merged