Upload 1738: UI: unusable when ran with cloud storage backends
CDCgov/data-exchange-upload pull request #519
Opened 2024-10-01 18:58 UTC by Sun-Mountain

2024-10-03 13:37 UTC, cfarmer-fearless commented on upload-server/internal/ui/ui.go
> +		loc = strings.Split(loc, "+")[0]
Let's reconsider this solution.  We may not need to parse the ID to a UUID at all.

2024-10-03 15:45 UTC, Sun-Mountain commented on upload-server/internal/ui/ui.go
> +		loc = strings.Split(loc, "+")[0]
The way I interpreted this is that you don't care if there's that long tus string is attached to the url?

2024-10-04 14:27 UTC, cfarmer-fearless requested changes

2024-10-04 14:27 UTC, cfarmer-fearless commented on upload-server/internal/ui/ui.go
> +		uuid = strings.Split(uuid, "/files/")[1]
Let's keep using `filepath.Base` instead of `strings.Split` as it's more robust.

2024-10-04 14:27 UTC, cfarmer-fearless commented on upload-server/docker-compose.azurite.yml
> +      # - DEX_MANIFEST_CONFIG_CONTAINER_NAME=config
Reason for commenting this out?

2024-10-04 14:27 UTC, cfarmer-fearless commented on upload-server/docker-compose.minio.yml
> +      # - DEX_MANIFEST_CONFIG_BUCKET_NAME=upload-configs
Reason for commenting this out?

2024-10-04 14:38 UTC, Sun-Mountain commented on upload-server/docker-compose.minio.yml
> +      # - DEX_MANIFEST_CONFIG_BUCKET_NAME=upload-configs
Removed now that we no longer need this variable.

2024-10-04 14:39 UTC, Sun-Mountain commented on upload-server/docker-compose.azurite.yml
> +      # - DEX_MANIFEST_CONFIG_CONTAINER_NAME=config
Removed now that we no longer need this variable.

2024-10-04 16:09 UTC, cfarmer-fearless approved these changes

2024-10-04 18:21 UTC, merged