UPLOAD-1740 updating the README
CDCgov/data-exchange-upload pull request #520
Opened 2024-10-02 15:38 UTC by thetif

- moved the `.env.example` file to `/upload-server` so that it could be used by the docker configs
- added all environment variables to the `.env.example` and added comments to clarify their uses to the user
- cleaned up code where necessary

2024-10-03 13:08 UTC, thetif commented on upload-server/internal/appconfig/appconfig.go
> -	TusUIInfoEndpointUrl string `env:"TUS_UI_INFO_ENDPOINT_URL, default=http://localhost:8080/info/"`
Added `SERVER_PROTOCOL`, `SERVER_HOSTNAME`, and `TUSD_HANDLER_INFO_PATH` so that we could remove `TUS_UI_FILE_ENDPOINT_URL` and `TUS_UI_INFO_ENDPOINT_URL` because they were dependent on SERVER_PORT in a way that might not be intuitive to the user

2024-10-03 13:08 UTC, thetif commented on upload-server/.env.example
> +########################
Added all the possible environment variables here, grouped them by use, and added comments to make things clearer

2024-10-03 13:09 UTC, thetif commented on upload-server/Dockerfile
> +ENTRYPOINT [ "./dextusd" ]
Switched from `CMD` to `ENTRYPOINT` so that we can pass in addition flags when running the container

2024-10-03 13:10 UTC, thetif commented on upload-server/cmd/cli/flags.go
> -	FileHooksDir  string
We're not actually using this flag anywhere so I removed it

2024-10-03 13:11 UTC, thetif commented on upload-server/cmd/main.go
> +	// ------------------------------------------------------------------
not sure if we were intentionally removing the flags or if it was removed by mistake, but added it back so that we could pass in the `.env` file for the configs

alternatively, we could have it use a `.env` by default if there is one present in the same directory

2024-10-03 13:12 UTC, thetif commented on upload-server/internal/appconfig/appconfig.go
> +	EhdiS3Connection    *S3StorageConfig `env:", prefix=EHDI_S3_, noinit"`
Added the missing destination types

2024-10-03 13:14 UTC, thetif commented on upload-server/internal/appconfig/appconfig.go
> +		if ac.AzureConnection.StorageName == "" || ac.AzureConnection.StorageKey == "" {
if only the AZURE_STORAGE_KEY is set, then AzureConnection is not nil and it tries to start up but fails. Added checks to see if both values we need are set and if not then I set AzureConnection to nil

2024-10-03 13:14 UTC, thetif commented on upload-server/internal/appconfig/appconfig.go
> +	if ac.S3Connection != nil {
similar to the AzureConnection

2024-10-07 13:10 UTC, MegMurray approved these changes
Looks great, Tif!

2024-10-08 13:16 UTC, AJKimpo approved these changes
This all looks good from my perspective; please have Chase review prior to merging

2024-10-08 13:50 UTC, cfarmer-fearless requested changes
Some minor changes but looks great overall

2024-10-08 13:50 UTC, cfarmer-fearless commented on upload-server/.env.example
> +DEX_MANIFEST_CONFIG_BUCKET_NAME=
Add a comment saying only one of the bucket or the folder env vars are necessary, not both

2024-10-08 13:50 UTC, cfarmer-fearless commented on upload-server/.env.example
> +# Azure routing container
These routing guys can be removed

2024-10-08 13:50 UTC, cfarmer-fearless commented on upload-server/internal/appconfig/appconfig.go
> +		if ac.AzureConnection.StorageName == "" || ac.AzureConnection.StorageKey == "" {
Let's fail a bit louder here.  If there isn't enough info to connect, the app should fail to start.  Same for S3

2024-10-08 13:50 UTC, cfarmer-fearless commented on upload-server/readme.md
> +- Support for multiple formats (JSON, XML)
This bullet point may needs to be expanded a bit.  Multiple formats for what?

2024-10-08 14:13 UTC, thetif commented on upload-server/readme.md
> +- Support for multiple formats (JSON, XML)
I stole that part from @MegMurray. :D I guess multiple file formats since we aren't really restricting anything

2024-10-08 14:13 UTC, thetif commented on upload-server/readme.md
> +> Never check your `.env` file into source control. It should only be on your local computer or on the server you are using it on.
there is, I just wanted to make sure no one removed it because they thought they came up with a great idea to share their passwords with the team

2024-10-08 14:14 UTC, thetif commented on upload-server/.env.example
> +PROCESSING_STATUS_HEALTH_URI=
cool, I wasn't sure what that was for but I didn't want to removed it if we needed it

2024-10-08 15:43 UTC, thetif commented on upload-server/internal/appconfig/appconfig.go
> +			return AppConfig{}, fmt.Errorf("missing required values for connecting to Azure")
I tried but Go did no like that, I think I could if we were returning a pointer to the config instead of the whole config

2024-10-08 15:43 UTC, thetif commented on upload-server/readme.md
> +- Support for multiple file formats (e.g., JSON, XML)
yes, I'll add uploads to that

2024-10-08 16:21 UTC, whytheplatypus requested changes

2024-10-08 16:21 UTC, whytheplatypus commented on upload-server/cmd/main_test.go
> +var AZURITE_KEY = os.Getenv("AZURE_STORAGE_KEY")
suggest leaving this as "AZURITE_STORAGE_KEY" to separate it for testing.

2024-10-08 16:21 UTC, whytheplatypus commented on upload-server/docker-compose.azurite.yml
> +      - TUS_AZURE_CONTAINER_NAME=${TUS_AZURE_CONTAINER_NAME:-test}
is the usecase for these env overrides for if you want to run this upload-server config without azurite?

2024-10-08 16:21 UTC, whytheplatypus commented on upload-server/internal/appconfig/appconfig.go
> +		} else if ac.AzureConnection.ContainerEndpoint == "" {
```suggestion
		} 
		if ac.AzureConnection.ContainerEndpoint == "" {
```

shouldn't need the else because of the early return.

2024-10-08 16:21 UTC, whytheplatypus commented on upload-server/testing/cli_test.go
> +	uiHandler := ui.GetRouter(ts.URL+appConfig.TusdHandlerBasePath, ts.URL+appConfig.TusdHandlerInfoPath)
it looks like these values will only be populated if `ParseConfig` is called

2024-10-08 16:26 UTC, thetif commented on upload-server/testing/cli_test.go
> +	uiHandler := ui.GetRouter(ts.URL+appConfig.TusdHandlerBasePath, ts.URL+appConfig.TusdHandlerInfoPath)
maybe I'm miss understanding how appconfig.go works, but I don't think that's the case, it seems to create it fine without the flag

2024-10-08 16:47 UTC, whytheplatypus commented on upload-server/testing/cli_test.go
> +	uiHandler := ui.GetRouter(ts.URL+appConfig.TusdHandlerBasePath, ts.URL+appConfig.TusdHandlerInfoPath)
yup ignore me i was look at this and misread url vs path https://github.com/CDCgov/data-exchange-upload/pull/520/files#diff-81f4a76d0fca50bb683250ae015cebfbfd13708b4a189a04f9609015aa71310fR308-R309

2024-10-08 17:01 UTC, thetif commented on upload-server/docker-compose.azurite.yml
> +      - TUS_AZURE_CONTAINER_NAME=${TUS_AZURE_CONTAINER_NAME:-test}
yes, but I guess for this and minio we don't really need to have those values be configurable. I'll switch those back

2024-10-08 17:10 UTC, thetif commented on upload-server/docker-compose.azurite.yml
> +      - TUS_AZURE_CONTAINER_NAME=${TUS_AZURE_CONTAINER_NAME:-test}
I was mostly changing things so that the ports would be configurable in the docker-compose and then I think I got carried away

2024-10-09 15:45 UTC, whytheplatypus approved these changes

2024-10-10 20:02 UTC, cyber-decker approved these changes
Changes look great!  Thanks for the clarity edits on the env-configs readme!  Much much improved.

2024-10-10 20:37 UTC, cfarmer-fearless approved these changes

2024-10-10 20:42 UTC, merged