nearly final version
CDCgov/data-exchange-upload pull request #524
Opened 2024-10-07 16:49 UTC by emilio32-lang

- yml using type: s3, az-blob, file
- path template, removed from manifest json
- removed all references to edav, ehdi, eicrs, ncird, routing from code

2024-10-08 15:05 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +var opMap = map[string]opFunc{
Could simplify this with a public `Destination` method that returns `(Destination, error)` and uses the create methods as private methods.  Something like...
```GoLang
func (t Target) Destination(ctx) (Destination, error) {
  switch t.type
    case "s3"
      return t.createS3Destination(ctx)
    case "az-blob"
      return t.createAzBlobDestination(ctx)
    case "file"
      return t.createLocalDestination()
    default
       return error target type not supported

}
```

2024-10-08 15:06 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +func unmarshalDeliverYML() (map[string][]Program, error) {
Replace "YML" with "Config" in the function name.

2024-10-08 15:07 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +	targetsMap := make(map[string]interface{})
Can you say `make(map[string][]Program)`?

2024-10-08 15:09 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +	for key, value := range targetsMap {
This loop and switch seem unnecessary.  Should just unmarshal straight to the `Program` type

2024-10-08 15:11 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +		return fmt.Errorf("failed to register destination targets")
The `unmarshalDeliveryYML` function should probably handle an error like this.

2024-10-08 15:12 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +		return fmt.Errorf("failed to register destination targets")
It should be ok if a program has no targets.  In fact, we should just default to file.

2024-10-08 15:13 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +			Month:    strconv.Itoa(int(t.Month())),
Keep the `fmt.Sprintf("%02d", t.Month())` way of doing this so it will pad single digit month and day with a zero.

2024-10-08 15:14 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +			return fmt.Sprintf("%s.%s", b.String(), extension), nil
Revert this change.  The `extension` variable already has a leading `.` character.

2024-10-08 15:15 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.yml
> +version: 1.0
Should only have one `deliver.yml` file

2024-10-08 15:16 UTC, cfarmer-fearless commented on upload-server/configs/deliver.yml
> +version: 1.0
Let's move this to the root project level so it'll be easier for it to be copied into the docker image

2024-10-08 16:45 UTC, whytheplatypus requested changes

2024-10-08 16:45 UTC, whytheplatypus commented on upload-server/configs/config.go
> +//go:embed deliver.yml
move to dynamically loading the config file.

2024-10-08 16:45 UTC, whytheplatypus commented on upload-server/internal/delivery/deliver.go
> +type Target struct {
Can specify a custom [UnmarshalYAML](https://pkg.go.dev/gopkg.in/yaml.v3?utm_source=godoc#Unmarshaler) function to handle this.

2024-10-08 16:45 UTC, whytheplatypus commented on upload-server/internal/delivery/deliver.go
> +	AwsRegion          string `yaml:"aws_region"`
these type specific variables can be contained in their own types, potentially directly the appropriate destination. The logic for splitting them out can be in the custom UnmarshalYAML function

2024-10-08 17:00 UTC, emilio32-lang commented on upload-server/internal/appconfig/appconfig.go
> +	DexCheckpointContainer string `env:"DEX_CHECKPOINT_CONTAINER_NAME, default=dex-checkpoint"`
removed

2024-10-08 17:03 UTC, whytheplatypus commented on upload-server/cmd/cli/route.go
> +	if _, ok := delivery.GetDestinationTarget(body.DataStreamId, body.DataStreamRoute, body.Target); !ok {
This feels like an increase in complexity to me, coupling the datastream/route and the target. If it's a security thing I get that, but then I wonder if we should use the information stored with the uploaded file rather than allow it to be passed in.

2024-10-08 19:29 UTC, emilio32-lang commented on upload-server/configs/deliver.yml
> +      - name:                     -ncird
resolved

2024-10-08 19:29 UTC, emilio32-lang commented on upload-server/internal/appconfig/appconfig.go
> +	DexCheckpointContainer string `env:"DEX_CHECKPOINT_CONTAINER_NAME, default=dex-checkpoint"`
resolved

2024-10-08 19:33 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +	fromPathStr := appConfig.LocalFolderUploadsTus + "/" + appConfig.TusUploadPrefix
reverted

2024-10-08 19:35 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +func GetRegisteredTargets() []any {
discussed it. Have some problems with the health check registrations.
Leave it as it is for now.

2024-10-08 19:36 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +func unmarshalDeliverYML() (map[string][]Program, error) {
replaced

2024-10-08 19:36 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +			Month:    strconv.Itoa(int(t.Month())),
reverted

2024-10-08 19:37 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +			return fmt.Sprintf("%s.%s", b.String(), extension), nil
reverted

2024-10-08 19:37 UTC, emilio32-lang commented on upload-server/configs/deliver.yml
> +version: 1.0
could not be done easily, without moving the go code as well.
Leave it as is for the moment

2024-10-08 22:49 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +	targetsMap := make(map[string]interface{})
addressed by Chase

2024-10-08 22:50 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +	for key, value := range targetsMap {
addressed by Chase

2024-10-08 22:50 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.yml
> +version: 1.0
removed the duplicate

2024-10-08 22:51 UTC, emilio32-lang commented on upload-server/internal/appconfig/appconfig.go
> +	DexCheckpointContainer string `env:"DEX_CHECKPOINT_CONTAINER_NAME, default=dex-checkpoint"`
removed

2024-10-08 23:31 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +		targetNames = append(targetNames, t)
updated

2024-10-09 11:58 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +			if t.Name[0] == '-' {
removed the code

2024-10-09 11:58 UTC, emilio32-lang commented on upload-server/internal/delivery/deliver.go
> +var opMap = map[string]opFunc{
implemented

2024-10-09 12:02 UTC, emilio32-lang commented on upload-server/cmd/cli/route.go
> +	if _, ok := delivery.GetDestinationTarget(body.DataStreamId, body.DataStreamRoute, body.Target); !ok {
updated, to get the data from the manifest

2024-10-10 20:32 UTC, cfarmer-fearless approved these changes

2024-10-11 13:43 UTC, merged