UPLOAD-1798/gha-playwright
CDCgov/data-exchange-upload pull request #528
Opened 2024-10-09 16:58 UTC by thetif

- created playwright docker-compose file
- added playwright tests to `tus-upload-server-ci.yml`, testing all upload locations
- changed some playwright configuration
- removed the endpoint field from the upload form because it is unnecessary and possibly destructive
- updated playwright tests to remove endpoint field and make them a little more fault tolerant

2024-10-17 13:35 UTC, thetif commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        // var refreshes = 0;
temporarily commented these tests out while we work out the new delivery situation, will probably need to make tests read from the delivery configs to know what the location should be

2024-10-17 13:36 UTC, thetif commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        // const fileDeliveriesContainer = page.locator('.file-deliveries-container');
temporarily commented these tests out while we work out the new delivery situation, will probably need to make tests read from the delivery configs to know what the location should be

2024-10-17 13:36 UTC, thetif commented on tests/smoke/playwright/test/upload-test.spec.ts
> +  const fileName = path.resolve(__dirname, 'test-data', '10KB-test-file');
moved the test file into the same directory so it's all contained

2024-10-17 13:39 UTC, thetif commented on upload-server/internal/appconfig/appconfig.go
> +	UIUrl     string
Before the port for the UI had to include the leading `:` which wasn't super intuitive, so I created the UIUrl field so that the port could just be the port

2024-10-17 13:41 UTC, thetif commented on upload-server/internal/appconfig/appconfig.go
> +	if ac.UIPort != "" {
creating the UIUrl if the port is set, otherwise UIUrl is set to empty string so that the UI won't start up if the UI_PORT is nil

2024-10-17 13:43 UTC, thetif commented on upload-server/internal/ui/ui.go
> +		uploadDestinationUrl, err := url.JoinPath(uploadUrl, id)
Removed the Endpoint field from the upload form because it wasn't needed, now passing in the uploadUrl that we are using as the endpoint for tus

2024-10-17 15:26 UTC, cfarmer-fearless requested changes

2024-10-17 15:26 UTC, cfarmer-fearless commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        // var refreshes = 0;
Would it be simpler to wait a certain amount of time (like 5 seconds) after an upload completes, and then check the status page as apposed to refreshing the page?  It's more of a "did we deliver the file in time" kind of approach, and that's what the kotlin tests do.

2024-10-17 15:26 UTC, cfarmer-fearless commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        await expect(fileHeaderContainer).toContainText(`ID: ${uploadId.split('+')[0]}`)
Hoping we can avoid this.  Ideally, these tests should have no awareness of the storage impl that the service under test is using.  Let's have a convo on how we are manipulating the ID at the presentation layer.

2024-10-17 15:26 UTC, cfarmer-fearless commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        // const fileDeliveriesContainer = page.locator('.file-deliveries-container');
Can the expected destinations be part of the test case? (again, this is how the kotlin tests do it)

2024-10-17 15:26 UTC, cfarmer-fearless commented on tests/smoke/playwright/wait-for-it.sh
> +#!/bin/bash
Why is this needed?  Doesn't playwright take care of this already?

2024-10-17 15:26 UTC, cfarmer-fearless commented on upload-server/Dockerfile
> +RUN addgroup -S -g 101 app && adduser -S -u 100 -G app app
What's the purpose of this change?  Maybe belongs in another PR

2024-10-17 15:26 UTC, cfarmer-fearless commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        // var refreshes = 0;
Regarding the new delivery config, you should be able to use the `DEX_DELIVERY_CONFIG_FILE` env var and the yml files defined in upload-server/configs/testing

2024-10-17 15:26 UTC, cfarmer-fearless commented on upload-server/internal/appconfig/appconfig.go
> +	UIUrl     string
If this is the only reason for splitting this config field, maybe we can change the underlying code to just include the `:`.  Unless there's a need for the service to be aware of the hostname, which I don't see any need for.

2024-10-17 16:27 UTC, thetif commented on upload-server/Dockerfile
> +RUN addgroup -S -g 101 app && adduser -S -u 100 -G app app
when Candace made her change to the previous part, it didn't seem to want to work for me until I did that. I can back it out and make it's not necessary now

2024-10-17 16:29 UTC, thetif commented on tests/smoke/playwright/wait-for-it.sh
> +#!/bin/bash
Playwright has a solution where it will start the server for you, but we can't use it because of the way the project is set up. If the server were Javascript it would be easy to do it. This is a work around because sometimes it can take much longer for the upload-server to start than the playwright, we can extend the timeout for the first test in every suite but that's not very durable.

2024-10-17 16:40 UTC, thetif commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        // var refreshes = 0;
yeah we definitely need to switch to using the config file, but that was outside the scope of this ticket. I had made that fix before the delivery stuff changed and then commented it out when it did.

2024-10-17 16:44 UTC, thetif commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        // var refreshes = 0;
we need to make a separate ticket to update everything based on the new configs, should make things easier too

2024-10-17 16:51 UTC, thetif commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        // const fileDeliveriesContainer = page.locator('.file-deliveries-container');
yes, that's what I was trying to do before the delivery stuff changed, and the delivery configs make it every easier to dynamically check for destinations

2024-10-17 16:52 UTC, thetif commented on upload-server/internal/appconfig/appconfig.go
> +	UIUrl     string
the NewServer expects it to be in that format and I was just going to set it there, but it seemed more sticking with the convention to set it in the appconfig because that's where we are creating all the other configs and maybe we will want to give the UI a hostname eventually

2024-10-17 16:55 UTC, thetif commented on tests/smoke/playwright/package.json
> +    "test": "npm run wait; npx playwright test",
Yes I was thinking we didn't really need it, but I thought it probably didn't hurt to have it check before running. It doesn't only wait for localhost:8081, it waits for whatever UI_URL is set to and defaults to localhost:8081 if it's not set.

2024-10-17 16:56 UTC, thetif commented on tests/smoke/playwright/playwright.config.ts
> +  retries: process.env.CI ? 2 : 0,
we can set it 0 all the time

2024-10-17 17:05 UTC, thetif commented on tests/smoke/playwright/test/upload-test-accessibility.spec.ts
> +        await page.goto(`/manifest?data_stream_id=dextesting&data_stream_route=testevent1`, { waitUntil: 'load' });
I think we could probably get rid of those, that was my first attempt before adding the wait-for-it

2024-10-17 17:06 UTC, thetif commented on .github/workflows/e2e-test-template.yml
> +        run: podman-compose -f ${{ inputs.COMPOSE_FILENAME }} up --build --exit-code-from playwright --abort-on-container-exit
oh good point, I didn't bring the continue-on-error over

2024-10-17 17:08 UTC, thetif commented on tests/smoke/playwright/test/upload-test-pages.spec.ts
> +        await expect(fileHeaderContainer).toContainText(`ID: ${uploadId.split('+')[0]}`)
Were we not able so resolve that filename tus string issue in S3? Or did Nicole run out of time before leaving? We should make a ticket to fix it if she just wasn't able to get to it in time

2024-10-17 17:11 UTC, cyber-decker commented on .github/workflows/e2e-test-template.yml
> +        run: podman-compose -f ${{ inputs.COMPOSE_FILENAME }} up --build --exit-code-from playwright --abort-on-container-exit
Perfect. I think for now, at least for the tests, if the playwright tests fail, lets be notified, but not stop the presses.   I want to make sure we can really trust the tests before we have them telling us that it should stop.

2024-10-25 20:54 UTC, cfarmer-fearless approved these changes

2024-10-25 21:25 UTC, merged