Decouple Delivery Targets From Route Groups
CDCgov/data-exchange-upload pull request #535
Opened 2024-10-18 13:04 UTC by cfarmer-fearless

This is an iteration on the deliver configuration schema.  The goal is to decouple delivery targets from routing groups.  This will improve robustness by preventing possible misconfiguration of creating multiple delivery targets with the same name.  With this, we want to make sure the server fails to start if the deliver yml is misconfiguration in this way.

2024-10-22 12:50 UTC, whytheplatypus commented on upload-server/internal/postprocessing/postprocessor.go
> +	d, ok := delivery.GetGroupTarget(dataStreamId, dataStreamRoute, e.DestinationTarget)
any concerns with reducing this down to `delivery.GetTarget(e.DestinationTarget)`?

2024-10-25 18:10 UTC, cfarmer-fearless commented on upload-server/internal/postprocessing/postprocessor.go
> +	d, ok := delivery.GetGroupTarget(dataStreamId, dataStreamRoute, e.DestinationTarget)
Yes.  It's a many:many relationship between groups and targets, so in order to get a target, we need to know the data stream and route, as well as the target name

2024-10-28 14:35 UTC, whytheplatypus requested changes

2024-10-28 14:35 UTC, whytheplatypus commented on upload-server/configs/testing/s3_destinations.yml
> +  - name: edav
this can be turned into a map so it deserializes naturally into a `map[string]destination`

2024-10-28 14:35 UTC, whytheplatypus commented on upload-server/configs/testing/s3_destinations.yml
>        - name: edav
the `name` key is redundant this can be an array of strings (similar to something like `depends_on` on in a compose file

2024-10-28 14:35 UTC, whytheplatypus commented on upload-server/configs/testing/s3_destinations.yml
>          path_template: $EICR_PATH_TEMPLATE
move this into the target definition.

2024-10-28 14:35 UTC, whytheplatypus commented on upload-server/internal/delivery/deliver.go
> +	if err := health.Register(getDeliveryHealthChecks([]Source{src}, dests)...); err != nil {
call this twice rather than use getDeliveryHealthChecks for clarity

2024-10-29 18:20 UTC, cfarmer-fearless commented on upload-server/configs/testing/s3_destinations.yml
>          path_template: $EICR_PATH_TEMPLATE
The path template? That should be decided by the route group, right?

2024-10-29 19:52 UTC, whytheplatypus approved these changes

2024-10-29 19:53 UTC, merged