delete raw uploads script
CDCgov/data-exchange-upload pull request #541
Opened 2024-10-23 15:44 UTC by rohitpanwar

2024-10-24 18:04 UTC, cfarmer-fearless requested changes
Some improvements to be made.  Considering this needs to search through millions of files, I think it's worth it to spend the development time now to make this more robust so the searching is faster down the road.  Specifically with parallelism with go routines and blob indexing.

I also suggest renaming the "upload-scripts" folder to "upload-data-gov" as this tool might turn into a more general data governance tool.

2024-10-24 18:04 UTC, cfarmer-fearless commented on upload-scripts/delete-raw-uploads.go
> +    	}
Fix formatting here

2024-10-24 18:04 UTC, cfarmer-fearless commented on upload-scripts/delete-raw-uploads.go
> +    	}
Run `go fmt ./...`

2024-10-24 18:06 UTC, cfarmer-fearless commented
Once this gets more solidified, please add a basic readme

2024-11-05 19:54 UTC, cfarmer-fearless requested changes
See above comments.  Also got the following error when running on GFE
```
2024/11/05 14:51:58 Failed to list blobs: GET https://ocioededataexchangedev.blob.core.windows.net/bulkuploads
--------------------------------------------------------------------------------
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ERROR CODE: AuthenticationFailed
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:68615e98-001e-0059-03bc-2fe995000000
Time:2024-11-05T19:51:58.8434953Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'oRfmwqg6nJGDEGPlJQRbeE3ed+6TNGSsbNvNW7r0/LE=' is not the same as any computed signature. Server used following string to sign: 'GET











x-ms-date:Tue, 05 Nov 2024 19:51:58 GMT
x-ms-version:2024-08-04
/ocioededataexchangedev/bulkuploads
comp:list
prefix:tus-prefix/
restype:container'.</AuthenticationErrorDetail></Error>
--------------------------------------------------------------------------------
exit status 1
```

2024-11-05 19:54 UTC, cfarmer-fearless commented on upload-scripts/main.go
> +				data_stream :=  metadata["meta_destination_id"]
Will this skip files with `data_stream_id` and `data_stream_route` in their metadata?

2024-11-05 19:54 UTC, cfarmer-fearless commented on upload-scripts/main.go
> +	if(ACCOUNT_KEY == "") {
This will always evaluate to true

2024-11-05 19:54 UTC, cfarmer-fearless commented on upload-scripts/main.go
> +		envKey := fmt.Sprintf("ACCOUNT_KEY_%s", strings.ToUpper(*TARGET_ENV))
So the actual environment variable that users need to set is `ACCOUNT_KEY_DEV` or `ACCOUNT_KEY_TST` etc?  And not just `ACCOUNT_KEY` as the readme suggests?  Kinda confusing and seems unnecessary.  Should just be `ACCOUNT_KEY`

2024-11-13 17:50 UTC, whytheplatypus requested changes

2024-11-13 17:50 UTC, whytheplatypus commented on upload-scripts/main.go
> +		}
if both match as tags this will return a duplicate result

2024-11-13 17:50 UTC, whytheplatypus commented on upload-scripts/main.go
> +		}
will result in duplicate results. could skip if it's an `info` file?

2024-11-14 13:30 UTC, cfarmer-fearless commented on upload-scripts/main.go
> +		}
Good point.  I think you're right.  I need to flip the logic here.  Skip if .info; otherwise start trying to match.  And if we are inspecting an actual file, we can pretty much guarantee the info file exists.

2024-11-14 13:35 UTC, cfarmer-fearless commented on upload-scripts/main.go
> +		}
Problem with this though is it may leave some zombie .info files.  Maybe that's ok

2024-11-14 15:59 UTC, whytheplatypus approved these changes

2024-11-14 16:06 UTC, merged