Integrate code from lib-cloud-proxy-go into routing delivery
CDCgov/data-exchange-upload pull request #550
Opened 2024-10-29 21:01 UTC by marcia-schulman

Adding functionality to Source and Destination types to support cross-cloud large file copies.

2024-11-01 13:45 UTC, cfarmer-fearless commented on upload-server/internal/delivery/azure.go
> +const maxPartsAzure = 50000
Wonder if these two should be at the config level.  They look like things that belong in a helm chart.

2024-11-01 13:52 UTC, cfarmer-fearless commented on upload-server/internal/delivery/azure.go
> +		if routines >= concurrency {
This check and additional wait seem unnecessary.  The wait on line 243 should suffice

2024-11-01 13:55 UTC, cfarmer-fearless commented on upload-server/internal/delivery/azure.go
> +	case err := <-errCh:
What's the behavior we want here?  Do we need to make sure all blocks staged successfully?  Is it all or nothing?  Or can we recover if we get errors for only a few?

2024-11-01 13:57 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +	Copy(ctx context.Context, path string, source *Source, metadata map[string]string, length int64, concurrency int) (string, error)
Do you need to pass in path, metadata, and length if passing in source?  Can those things be gotten from the source?

2024-11-04 23:11 UTC, marcia-schulman commented on upload-server/internal/delivery/azure.go
> +		if routines >= concurrency {
changed to use work pool

2024-11-04 23:12 UTC, marcia-schulman commented on upload-server/internal/delivery/azure.go
> +	case err := <-errCh:
due to automatic staging retries, if it gets this far, it is best to abort.

2024-11-04 23:12 UTC, marcia-schulman commented on upload-server/internal/delivery/deliver.go
> +	Copy(ctx context.Context, path string, source *Source, metadata map[string]string, length int64, concurrency int) (string, error)
no :)

2024-11-05 21:43 UTC, cfarmer-fearless requested changes
Some relatively minor polishing but overall looks great.  I also want to see the unit tests a bit more robust by creating any storage containers on the fly so they can work in a CI pipeline

2024-11-05 21:43 UTC, cfarmer-fearless commented on upload-server/internal/appconfig/appconfig.go
> +	MaxConcurrency int `env:"MAX_CONCURRENCY, default=500"`
This can be named a bit more specific like `MAX_DELIVERY_CONCURRENCY` since we have another environment variable for setting routing event handler worker pools.

2024-11-05 21:43 UTC, cfarmer-fearless commented on upload-server/internal/delivery/azure.go
> +const maxPartsAzure = 50000 // maximum number of parts per block blob in Azure Storage
Let's include the units in the names, and also move this to app config

2024-11-05 21:43 UTC, cfarmer-fearless commented on upload-server/internal/delivery/azure.go
> +	props["last_modified"] = resp.LastModified.Format(time.RFC3339Nano)
Should setting the last modified and content length properties be moved to a higher level operation like a hook?  Setting them within `GetMetadata` seems like a side-effect

2024-11-05 21:43 UTC, cfarmer-fearless commented on upload-server/internal/delivery/azure.go
> +		Read:   true,
Might be best if these permissions are passed into the function, that way we can do least privilege if need be.

2024-11-05 21:43 UTC, cfarmer-fearless commented on upload-server/internal/delivery/azure.go
> +	numChunks := length / partSize
Do we need to worry about any truncation here?

2024-11-05 21:43 UTC, cfarmer-fearless commented on upload-server/internal/delivery/azure.go
> +			case errCh <- err:
Do we need this select here?  Don't we just want to do `errCh <- err` and return?

2024-11-05 21:43 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +	if maxConcurrency <= 0 {
We can just default the `MaxConcurrency` to 500 in the app config

2024-11-05 21:43 UTC, cfarmer-fearless commented on upload-server/internal/delivery/deliver.go
> +		length = 1
Does setting the length to 1 mean we fall back to the old way of copying the file?

2024-11-05 21:43 UTC, cfarmer-fearless commented on upload-server/internal/delivery/s3.go
> +			case errCh <- err:
Is this select necessary?  Just `errCh <- err` and return, right?

2025-03-11 15:57 UTC, cfarmer-fearless commented
Closing due to staleness

2025-03-11 15:57 UTC, closed without merging